--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVE
--------------------------------------------------------

  CREATE TABLE "SPACETIME"."RESERVE" 
   (	"RESERVE_NO" NUMBER, 
	"RESERVE_COUNT" NUMBER DEFAULT 1, 
	"RESERVE_DATE" DATE DEFAULT SYSDATE, 
	"USE_DATE" DATE, 
	"START_TIME" NUMBER, 
	"END_TIME" NUMBER, 
	"PRICE" NUMBER, 
	"SPACE_NO" NUMBER, 
	"MEM_NO" NUMBER, 
	"RESERVE_STATUS" CHAR(1 BYTE) DEFAULT 'W', 
	"DENY_MESSAGE" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SPACETIME"."RESERVE"."RESERVE_NO" IS '예약번호(시퀀스 SEQ_RNO으로 채번)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."RESERVE_COUNT" IS '예약인원(최대수용인원 초과시 예약 불가)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."RESERVE_DATE" IS '예약일자(INSERT 되는 시간)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."USE_DATE" IS '이용일';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."START_TIME" IS '이용시작시간';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."END_TIME" IS '이용종료시간';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."PRICE" IS '총결제금액';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."SPACE_NO" IS '공간번호 (FK)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."MEM_NO" IS '회원번호 (FK)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."RESERVE_STATUS" IS '예약상태(W:예약대기/Y:예약확정/N:예약거절/C:사용자취소)';
   COMMENT ON COLUMN "SPACETIME"."RESERVE"."DENY_MESSAGE" IS '예약거절메세지(거절사유)';
REM INSERTING into SPACETIME.RESERVE
SET DEFINE OFF;
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (1,3,to_date('22/08/07','RR/MM/DD'),to_date('22/08/08','RR/MM/DD'),14,17,30000,178,2,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (2,120,to_date('22/07/01','RR/MM/DD'),to_date('22/07/02','RR/MM/DD'),0,24,200000,197,2,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (3,1,to_date('22/12/15','RR/MM/DD'),to_date('22/12/16','RR/MM/DD'),2,3,19000,1,3,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (4,120,to_date('22/07/03','RR/MM/DD'),to_date('22/07/07','RR/MM/DD'),0,24,200000,197,3,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (5,1,to_date('22/12/21','RR/MM/DD'),to_date('22/12/22','RR/MM/DD'),2,3,19000,1,3,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (6,50,to_date('22/07/04','RR/MM/DD'),to_date('22/07/10','RR/MM/DD'),8,18,20000,147,4,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (7,2,to_date('22/07/10','RR/MM/DD'),to_date('22/07/25','RR/MM/DD'),9,20,10000,391,5,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (8,32,to_date('22/07/17','RR/MM/DD'),to_date('22/07/23','RR/MM/DD'),11,20,50000,397,6,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (9,20,to_date('22/07/22','RR/MM/DD'),to_date('22/07/26','RR/MM/DD'),0,24,19000,194,7,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (10,200,to_date('22/07/30','RR/MM/DD'),to_date('22/07/10','RR/MM/DD'),8,23,3850000,387,8,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (11,8,to_date('22/07/01','RR/MM/DD'),to_date('22/07/03','RR/MM/DD'),10,23,20000,349,9,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (12,12,to_date('22/07/04','RR/MM/DD'),to_date('22/07/05','RR/MM/DD'),0,24,149000,141,10,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (13,30,to_date('22/07/10','RR/MM/DD'),to_date('22/07/20','RR/MM/DD'),9,21,130000,117,11,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (14,8,to_date('22/07/11','RR/MM/DD'),to_date('22/07/23','RR/MM/DD'),0,24,110000,198,12,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (15,2,to_date('22/01/03','RR/MM/DD'),to_date('22/01/07','RR/MM/DD'),10,12,20000,1,13,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (16,6,to_date('22/01/04','RR/MM/DD'),to_date('22/01/10','RR/MM/DD'),10,20,100000,2,14,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (17,30,to_date('22/01/10','RR/MM/DD'),to_date('22/01/25','RR/MM/DD'),10,22,300000,3,15,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (18,3,to_date('22/01/17','RR/MM/DD'),to_date('22/01/23','RR/MM/DD'),13,15,100000,4,16,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (19,3,to_date('22/01/22','RR/MM/DD'),to_date('22/01/26','RR/MM/DD'),15,17,20000,5,17,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (20,27,to_date('22/01/30','RR/MM/DD'),to_date('22/02/10','RR/MM/DD'),12,19,70000,6,18,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (21,10,to_date('22/02/01','RR/MM/DD'),to_date('22/02/03','RR/MM/DD'),19,24,100000,7,19,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (22,3,to_date('22/02/04','RR/MM/DD'),to_date('22/02/05','RR/MM/DD'),8,18,60000,8,20,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (23,5,to_date('22/02/10','RR/MM/DD'),to_date('22/02/20','RR/MM/DD'),9,19,200000,9,21,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (24,30,to_date('22/08/22','RR/MM/DD'),to_date('22/08/23','RR/MM/DD'),0,24,35000,30,22,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (25,6,to_date('22/07/23','RR/MM/DD'),to_date('22/07/24','RR/MM/DD'),10,24,15000,188,23,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (26,6,to_date('22/08/09','RR/MM/DD'),to_date('22/08/10','RR/MM/DD'),11,22,10000,570,24,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (27,15,to_date('22/08/11','RR/MM/DD'),to_date('22/08/12','RR/MM/DD'),0,24,27500,376,25,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (28,4,to_date('22/08/24','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),0,24,7000,15,26,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (29,15,to_date('22/07/24','RR/MM/DD'),to_date('22/07/25','RR/MM/DD'),0,24,27500,376,27,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (30,7,to_date('22/07/26','RR/MM/DD'),to_date('22/07/27','RR/MM/DD'),9,24,2000,383,28,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (31,30,to_date('22/08/13','RR/MM/DD'),to_date('22/08/14','RR/MM/DD'),0,24,20000,549,29,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (32,8,to_date('22/08/26','RR/MM/DD'),to_date('22/08/27','RR/MM/DD'),0,24,33000,20,30,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (33,8,to_date('22/08/15','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'),0,24,100000,566,31,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (34,6,to_date('22/07/27','RR/MM/DD'),to_date('22/07/28','RR/MM/DD'),8,23,15000,375,32,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (35,12,to_date('22/08/28','RR/MM/DD'),to_date('22/08/29','RR/MM/DD'),0,24,30000,300,33,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (36,10,to_date('22/08/30','RR/MM/DD'),to_date('22/08/31','RR/MM/DD'),0,24,50000,247,34,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (37,10,to_date('22/07/29','RR/MM/DD'),to_date('22/07/30','RR/MM/DD'),0,24,85000,215,35,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (38,4,to_date('22/08/16','RR/MM/DD'),to_date('22/08/17','RR/MM/DD'),0,24,20000,550,36,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (39,20,to_date('22/08/17','RR/MM/DD'),to_date('22/08/18','RR/MM/DD'),11,22,20000,559,37,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (40,6,to_date('22/08/01','RR/MM/DD'),to_date('22/08/02','RR/MM/DD'),0,24,20000,173,38,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (41,18,to_date('22/09/01','RR/MM/DD'),to_date('22/09/02','RR/MM/DD'),0,24,44000,13,39,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (42,10,to_date('22/08/18','RR/MM/DD'),to_date('22/08/19','RR/MM/DD'),6,23,10000,567,40,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (43,10,to_date('22/08/02','RR/MM/DD'),to_date('22/08/03','RR/MM/DD'),0,24,2500,191,41,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (44,10,to_date('22/09/02','RR/MM/DD'),to_date('22/09/03','RR/MM/DD'),0,24,8500,272,42,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (45,4,to_date('22/08/19','RR/MM/DD'),to_date('22/08/20','RR/MM/DD'),6,22,15000,581,43,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (46,6,to_date('22/08/04','RR/MM/DD'),to_date('22/08/05','RR/MM/DD'),8,22,30000,219,44,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (47,6,to_date('22/09/04','RR/MM/DD'),to_date('22/09/05','RR/MM/DD'),6,24,20000,268,45,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (48,30,to_date('22/08/06','RR/MM/DD'),to_date('22/08/07','RR/MM/DD'),0,24,25000,415,46,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (49,6,to_date('22/09/05','RR/MM/DD'),to_date('22/09/06','RR/MM/DD'),6,24,20000,130,47,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (50,12,to_date('22/08/20','RR/MM/DD'),to_date('22/08/21','RR/MM/DD'),0,24,15000,586,48,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (51,15,to_date('22/08/21','RR/MM/DD'),to_date('22/08/22','RR/MM/DD'),0,24,33000,580,49,'Y',null);
Insert into SPACETIME.RESERVE (RESERVE_NO,RESERVE_COUNT,RESERVE_DATE,USE_DATE,START_TIME,END_TIME,PRICE,SPACE_NO,MEM_NO,RESERVE_STATUS,DENY_MESSAGE) values (52,6,to_date('22/09/06','RR/MM/DD'),to_date('22/09/07','RR/MM/DD'),0,24,20000,24,50,'Y',null);
--------------------------------------------------------
--  DDL for Index RESERVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPACETIME"."RESERVE_PK" ON "SPACETIME"."RESERVE" ("RESERVE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESERVE
--------------------------------------------------------

  ALTER TABLE "SPACETIME"."RESERVE" ADD CONSTRAINT "RESERVE_PK" PRIMARY KEY ("RESERVE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPACETIME"."RESERVE" ADD CONSTRAINT "RESERVE_STATUS_CK" CHECK (RESERVE_STATUS IN('W', 'Y', 'N','C')) ENABLE;
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("RESERVE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("SPACE_NO" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("USE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("RESERVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPACETIME"."RESERVE" MODIFY ("RESERVE_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RESERVE
--------------------------------------------------------

  ALTER TABLE "SPACETIME"."RESERVE" ADD CONSTRAINT "RESERVE_MEM_FK" FOREIGN KEY ("MEM_NO")
	  REFERENCES "SPACETIME"."MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "SPACETIME"."RESERVE" ADD CONSTRAINT "RESERVE_SPACE_FK" FOREIGN KEY ("SPACE_NO")
	  REFERENCES "SPACETIME"."SPACE" ("SPACE_NO") ENABLE;
