-- 경미
--행 1
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'우리가치 파티룸','한강뷰 복층 파티룸 크리스마스 트리 설치 완료!','한강뷰 복층 파티룸 크리스마스 트리 설치 완료 ♥<br>안녕하세요!<br>디자인과 예술을 사랑하는 오너가 만든 공간대여 [우리가치] 입니다.<br>• 생일, 브라이덜샤워, 원데이클래스, 스터디룸, 제품 촬영 등 다양한 이용<br>• 좌로는 한강, 우로는 국회의사당과 남산타워가 보이는 존예로운 통창뷰<br>• 홈카페를 위한 오너 수집품과 촬영용 감각적인 소품 배치<br>',10000,6,'서울 영등포구 양평로 11','당산리버뷰한강','05043220719','당산파티룸,연말모임,송년회,영등포파티룸,생일파티','Y',468,37.5322275957294,126.904658396345,0,24,2,1);
--행 2
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'하이퍼커피(hypercoffee)','어떠한 모임도 프라이빗하게 즐기실 수 있습니다.','평일 영업시간 (08:00~20:00) 일반 카페입니다.<br>생일파티, 각종모임, 쿠킹 클래스,스터디 모임, 촬영 등 프라이빗한 장소로 적합합니다.<br><br>14평 공간 실내화장실 외  테라스 1대 의 주차 공간이 있습니다.<br>카페음료 및 디저트를 합리적인 가격으로 즐기실수 있으며  편안한 분위기로 프라이빗한 시간을 보내실수 있습니다. <br>주간 5시간 정상 대관사용시 아메리카노(HOT&amp;ICE) 10잔이 제공됩니다.(심야제외)  대관시 모든 음료 10% 할인.<br><br>※시간 단위 대여는 공간대여 목적으로 하고있습니다※<br>-주간 대관시 직원이 거주 영업(take out 포장 , 배달운영) 하오니 이점확인바랍니다. (무인대관 협의가능)<br>-심야대관(20:00~07:00)은 11시간 풀타임 원칙운영으로 보증금이 있습니다.(심야 무인 운영)<br>-카페 장비 및 주방기구를 사용 하여 촬영, 강의등  주방 사용시 별도의 협의가 필요하오니 이점 꼭 유의바랍니다!<br>-대관 시간 금액 등 모두 협의하여 조율 가능합니다.',10000,20,'서울 구로구 구로동로 180','하이퍼커피','05071415109','카페대관,파티룸,공간대여,모임공간,소모임','Y',103,37.4945507331395,126.88305406002,0,24,7,2);
--행 3
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'목동 엠제이홀','서울 목동에 위치한 이벤트홀.공연장.연습실','서울 목동 오목교역 대로변 접근성좋은 초역세권에 위치한 공연장. 아트홀입니다.<br><br>엠제이홀은 50~60석 규모의 하우스콘서트. 마스터클래스,작은음악회, 입시 홀연습등에 적합한 홀입니다<br><br>요즘 코로나로인해 많은 음악회가 온라인으로 대체되면서 더더욱 찾는분이 늘어난 엠제이홀입니다.<br><br>수능이 끝나고 입시생들 입시모의 연주 &amp; 입시모의 평가로 가장 적합한 공간입니다.<br><br>공기청정기.냉난방.제습기.산소발생기를 통해 매우 쾌적한 공기와 환경을 관리하고 있으며<br><br>작은음악회,제자연주회,전공생들의 마스터클래스,홀연습,소규모 콩쿨,음대  음악회 리허설은 물론<br><br>앙상블연습,합창연습,오케스트라연습등도 가능합니다.<br><br>특히 요즘같은 코로나 시대 비대면 온라인 음악회.유튜브 촬영 방송 등에 최적화된 연주홀입니다<br><br>프로포즈대관,파티룸,기업의 세미나 용도로도 대관합니다.<br><br>객석 최대 60석. <br><br>코로나 시대의 비대면 음악회 &amp; 입시 리허설 &amp; 비대면 입시영상촬영 등에 가장 적합한 목동 엠제이홀 많이 이용해주세요!',25000,60,'서울 양천구 오목로54길 14','더클래식 지하1층','05041381469','목동음악연습실,목동피아노연습실,목동연습실,목동보컬연습실,목동그랜드피아노연습실,목동음악홀,목동공연장,공연장','Y',71,37.5233634981364,126.873020180463,0,24,14,3);
--행 4
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'사운드작업 악기연습실 스튜디오원','피아노, 기타, 보컬 등 음악연습 공간[뮤직룸]','피아노, 기타, 드럼, 마이크, 베이스, 스피커. 엠프 및 사운드 녹음 전용 공간입니다<br>방음시설 갖춰져있습니다.<br>(추가 구성 - 사운드 믹싱 서비스)<br><br>200w 난라이트 지속광 조명 2ea와 600w 포멕스 조명 3ea(동조기포함) 기본 제공됩니다.<br>카페테리아와 드레스룸(헤어메이크업)을 위한 공간, 진열되어 있는 다양한 소품들도 사용가능합니다.<br><br>건물 지하 2층부터 지하 5층까지 주차장을 이용하실 수 있으며 3시간마다 주차권을 발행해드립니다.<br><br>http://studioone.co.kr/default/<br>스튜디오의 자세한 정보는 위 홈페이지에서 확인해주세요!<br><br>위치 – 강서구 공항대로 194 퀸즈파크 12차 지하 1층 101, 102호',50000,10,'서울 강서구 공항대로 194','지하1층 B101호-102호','05043220057','피아노,보컬,음악연습,방음시설,기타연습,연습실','Y',34,37.5589717169884,126.828975748509,0,24,3,4);
--행 5
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'유니하니 베이킹 쿠킹 공유주방','베이킹 요리 및 파티를 즐길 수 있는 다목적 공간','안녕하세요! 유니하니 입니다 :)<br>유니하니 공유주방은 베이킹, 쿠킹, 요리 및 파티룸까지 누구나 이용 가능한 공간입니다.<br><br>■ 청소보증금 3만원이 입금되어야 예약확정됩니다.<br>[결제완료 후 문자안내]<br><br>※ 야간타임은 패키지(7시간)로만 운영됩니다.<br><br>1,2호선 신도림역 근처에 있어 찾아오시기 매우 편리합니다.<br>베이킹 공방 바로 옆에 주차 공간이 있으며, 근처에 편의점과 마트들이 있어 장 보시기에도 좋습니다.<br>기본적인 조리 도구와 양념이 있어 요리와 식사를 즐길 수 있습니다.<br>베이킹 원데이클래스나 유튜브 촬영으로 사용하실 수 있습니다.<br><br>베이킹과 요리, 파티가 가능한 공간에서 특별한 시간을 보내보아요!<br><br>■ 자세한 문의정보<br>인스타그램 : yuni_hani_<br>유튜브 : 유니하니 프로개발러',10000,8,'서울 구로구 공원로6가길 49','1층 유니하니','05043220768','베이킹,쿠킹,공유주방,파티룸,유니하니','Y',273,37.5034074436517,126.889902268129,0,24,21,5);
--행 6
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'갤러리 어반플루토','홍대,신촌,선유도역에서 가까운 전시 공간','2015년부터 운영 된 전시를 위해 특화 된 갤러리 어반플루토입니다. <br><br>1인 전시부터 단체 전시 졸업전시까지 다양한 전시가 가능합니다. <br><br>작품 발표가 필요한 창작자들에게 열린 공간 어반플루토의 문을 두드려 주세요. ^^<br><br>* 반드시 예약 전에 가능 여부 문의를 먼저 해주세요~!<br><br>* 예약은 1일 단위로만 가능하므로 예약하실 날짜를 개별적으로 예약해주세요.<br><br>* 추가 옵션은 첫날에만 선택해주세요.<br><br>홍대, 신촌, 합정, 당산, 선유도공원과 가까운<br>서울 영등포구 양평동 9호선 선유도역 2번 출구에 위치한<br>복합문화공간 어반플루토 갤러리에서 멋진 전시를 준비해보세요.<br><br>어반플루토는 9호선 선유도역 2분 거리에 있어요!<br><br>보다 상세한 안내 -&gt; http://www.urbanpluto.com/rent-gallery',10000,30,'서울 영등포구 양평로22나길 3-2','2층','05040905639','졸업전시,전시회,전시대관,갤러리대관,갤러리','Y',512,37.5388295793653,126.893977287717,12,19,26,6);
--행 7
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'정무문 에어연습실','등촌역/에어전문연습실/쿠션바닥/50평','정무문 에어연습실''은 50평 크기의 충격흡수가  되는 쿠션바닥으로 되어있어 에어 아크로바틱 등을 안전하게 연습할수있는 연습실입니다<br><br>*등촌역 도보 10분 거리<br>*연습실 한쪽벽면 거울 배치<br>*한쪽 면은 부상방지 및 물구나무 서기를 할수있는 쿠션닝 시공<br>*더 안전한 연습을 위한 매트 배치<br>*50평의 넓은 공간',20000,15,'서울 양천구 목3동 646-6','1층','05040905550','등촌역,50평,아크로바틱,연습실,에어,운동시설','Y',19,37.5460368756907,126.86464473835,19,24,9,7);
--행 8
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'르하임스터디카페 강서마곡점','공부가 잘되는 스터디카페, 모임하기 좋은 스터디룸','르하임 스터디카페 강서마곡점에는 다양한 스터디룸(8인실/4인실/2인실)이 있으며, <br>어떠한 형태의 그룹 학습이나 모임 등에도 최적화되어 있습니다. <br><br>스터디룸 뿐만 아니라 간단한 음료와 커피를 이용하면서 휴식할 수 있는 카페존과 <br>모임 전후 이용할 수 있는 스터디존이 있어, 조용하고 고급스러우면서 한 공간에서 <br>다른 시설들을 통해 시너지효과를 얻고자 하시면 적절한 선택이 될 것이라 확신합니다.<br><br>스터디카페는 24시간 연중무휴로 운영되며 스터디룸은 10시~22시까지 운영합니다.<br>기본 운영시간 외 스터디룸을 이용하고자 하시면 미리 연락주시기 바랍니다.<br><br>종일 이용을 원하시면 종일권을 이용하시면 좋습니다.<br>또한 매주 정기적으로 장기 이용을 원하시는 경우 10시간, 20시간 정액권을 이용하면<br>보다 효율적일 것입니다.<br><br>이용자의 입장에서 최선을 다하겠습니다.',6000,4,'서울 강서구 수명로 74','발산시티타워 3층','05040905110','4인실,셀프티칭,단체룸,마곡스터디카페,강서구스터디룸','Y',65,37.5525548220745,126.82620080065,5,24,18,8);
--행 9
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'마곡나루 비즈니스센터 소호사무실','9호선/공항철도 마곡나루역, 신규 비즈센터 회의실','- 회의실 대여 : 1~6인 회의실 <br>  ⋆ am 9:00~pm 22:00 대여가능<br>  ∙ 회의, 미팅, 스터디, 세미나를 위한 사양 완비 <br>  ∙ PT용 시설 구비<br>  ∙ 소형 회의실 및 미팅 공간 &amp; 카페<br>  ∙ 중대형 회의실 및 휴게 공간 &amp; 티테이블<br>  ∙ 복합기(복사,스캔,팩스)/프린터/빔프로젝터/세단기 등<br>  ∙ 정수기/원두커피머신/차&amp;다과 등<br> ⋆ 회의실 대여시 카페 이용 가능 (음료 제공)',20000,6,'서울 강서구 마곡중앙로 171','프라이빗타워2차 511호','05040905821','회의실,비즈니스센터,사무실,세미나실','Y',36,37.5690745516743,126.827718838457,9,22,28,9);
--행 10
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'크로마스튜디오','크로마키호리존트영상촬영스튜디오(스케줄전화문의필수)','가로 6m, 세로 (깊이)5.5m, 높이 3.5m의 호리존과 5m의 홀은 다양한 앵글의 촬영을 가능하게 해줍니다.<br>벽면이 만나는 모든 지점이 깔끔하게 3면 곡선으로 마감되어 있습니다.<br>기본 LED천장 조명외에 6대의 지속광 조명이 설치되어있어서 별도의 조명 세팅없이 기본 촬영이 가능합니다.<br>영등포구 양평동에 위치해 있어 목동 및 강서 지역과 마포 홍대쪽에서도 접근성이 용이합니다. <br>실 제작진이 제작환경 전반을 이해하고 직접 설계해놓은 GLUEHOUSE STUDIO에서 최고의 결과물을 얻으시길 바랍니다.<br>(스케줄전화문의필수)',66000,20,'서울 영등포구 영등포로5길 19','동아프라임밸리 701호','05040905353','목동,영등포,크로마,스튜디오,글루하우스,촬영스튜디오','Y',42,37.524273839112,126.884302974587,0,24,5,10);
--행 11
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'크리스마스 미국 가정집 겨울 컨셉','요리가능한 미국 가정집 주방컨셉의 따뜻한 스튜디오','미국가정집 컨셉의 촬영스튜디오 &amp; 파티룸입니다.<br><br>미국  가정집 주방 분위기를 연출하기 위하여 미국과 유럽 등에서 물건너온 앤틱소품과 현대적인 소품을 공간에 배치하여 꾸몄습니다.<br>*디즈니 백설이컨셉, 크리스마스 분위기 컨셉, 미국주방 느낌 등 컨셉 요청가능하십니다* <br><br>-&gt;당일 예약문의는 문자 또는 카톡주세요!! <br> <br>요리가 가능한 공간으로써 솔샤에 있는 조리도구 모두 사용가능하며<br><br>스냅사진, 유튜브 라이브 촬영, 라이브커머스, 명품촬영, 음식촬영, 컨셉 촬영, 브라이덜샤워, 베이비샤워, 생일파티,소모임, 원데이클래스 등이 가능합니다.<br><br>* 이동식 아일랜드 식탁, 테이블, 의자 10개 (작은의자포함), 42L 베이킹 오븐,  멀티쿠커 , 조리도구 , 150cm 크리스마스 트리 *<br> <br>6인이상시 추가 요금을 받고 있으며, <br>편의점, 서울식물원, LG 아트센터 등 편의시설이 갖춰줘 있습니다.<br><br><br>',35000,10,'서울 강서구 마곡동 760-2','  234호  솔샤스튜디오','05041381307','키친스튜디오,유튜브촬영,빈티지,파티룸,크리스마스,뮤직비디오','Y',130,37.5678285382276,126.827452877384,0,24,30,1);
--행 12
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'강서구 발산 마곡 등촌 파티룸','파티, 모임, 단독 공간이 필요할 때 베라 스튜디오','강서구  마곡, 발산, 등촌동 중심에 위치한  <br><br>모던하면서도 트렌디한 인테리어의  파티룸,  베라 스튜디오입니다.<br><br>발산역 도보7 분 거리(등촌동)에  위치해 있습니다.<br><br><br><br>생일 파티, 연말 모임, 기념일 모임, 소규모 모임, 커플 이벤트, 가족 모임, 돌잔치, 유튜브 등 영상 촬영  및 셀프 스튜디오로 공간 활용 가능합니다.<br><br><br>송년회, 연말모임 각종 행사나 워크샵 공간을 단독으로 한 팀만 프라이빗하게 사용하실 수 있습니다.<br><br><br>테이블과 미니 키친 공간이 있어 편하게 준비 하신 후 더욱 여유 있는 모임을 즐기실 수 있습니다.<br><br><br>기본 3시간 이상 부터 이용 가능합니다^^<br><br><br>또한 셀프 사진 촬영 가능합니다. 기념 사진, 스냅 사진, 단체 사진을 원하시는 경우 전문 포토그래퍼 촬영도 가능하니 따로 문의 주세요^^<br>',30000,12,'서울특별시 강서구 등촌동 696','세신그린코아 201호(베라스튜디오)','05040905611','파티룸,송년회모임,셀프스튜디오,동호회모임,원데이클래스','Y',178,37.5602518224346,126.84583388863,0,24,6,1);
--행 13
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'강서구 카페대관 WRU','통창과 넉넉한 주차공간! 새로운 감성을 안겨드려요','안녕하세요, 강서구 공항동에 위치한 WRU 입니다.<br><br>지하철 5호선 송정역 도보2분<br>9호선 공항시장역에서 도보4분 거리에 위치해 있습니다.<br><br>*세 곳의 통창과 넉넉한 주차공간 그리고 테라스까지, 확 트인 내부와 감각적인 플랜테리어가 어우러진 감성 공간입니다.*<br><br>조명은 조광기를 통해 밝게 또는 어둡게 연출이 가능합니다.<br><br>내부에 단독 화장실이 있어 보다 편리하게 이용 가능합니다.<br><br>벽에 빔 프로젝트를 이용해 영화감상,프로포즈,다른 공간 연출 가능합니다.<br><br>1층에 위치해있지만 반 층 올라와있어 도로와 분리되어 색다른 공간 연출 가능합니다.<br><br>남향으로 오전~낮 시간대에 인물이 잘 나오는 인터뷰촬영, SNS광고촬영, 쇼핑몰촬영등으로 인기 있습니다.',44000,18,'서울 강서구 공항대로7길 15','1층 흰 울타리 안','05043220716','강서구공간대여,강서구브라이덜샤워,공항동회의실,강서구장소대관,카페,공항동촬영','Y',89,37.562018765371,126.812291245728,0,24,7,2);
--행 14
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'마곡 북카페, 또 다른 여행','차분한 분위기 속 책과 커피가 함께하는 공간','넓고 햇살이 들어오는 차분한 분위기의 <br>책과 커피가 함께하는 북카페입니다.<br>8층에 위치하고 있어 독립적인 공간으로 활용가능하시며,<br>공간도 넓어 많은 사람 수용가능합니다.<br><br>대관 중에도 카페는 운영하고 있으므로 음료 및 베이커리 주문이 가능합니다.<br>만약 카페운영 없이 대관을 원하실 경우 사전에 말씀 주시기 바랍니다.<br><br>30~40명정도, 모임이나 파티, 행사, 사진 촬영 등으로 이용하실 수 있습니다.<br>원하시는 구성이 있으시다면 협의가능하니, 예약 전에 전화로 문의주시기 바랍니다.',100000,30,'서울 강서구 마곡중앙2로 35','이너매스2차 8층 젠요가 & 또다른여행','05041381237','마곡,북카페,소모임,세미나,회의','Y',411,37.5579716424954,126.830559683489,9,22,8,2);
--행 15
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'블랙우드 카페, 펍','강서구 가양동 35평 확트인 뷰 분위기 좋은 카페','안녕하세요^^<br>강서구 가양동 5층건물 2층에 위치한 35평규모  넓고 깔끔한 인테리어 로<br>분위기좋은  불랙우드 카페입니다.<br><br>생일파티 장소가 필요하신가요?<br><br>이벤트모임 장소가 필요하신가요?<br><br>프로포즈 계획 있으신분 장소 필요하신가요?<br><br>각종 파티/ 단체모임/ 스터디모임/세미나 장소 필요하신가요?<br><br>방송촬영 장소 필요하신가요?<br><br>각종 행사 나 파티 계획 으로 공간 필요하신분 소규모 부터 50인이하  음악회 주최까지  가능한 <br>블랙우드 카페&amp;펍  으로 부담갖지 마시고 대관 문의주세요.<br><br>깔끔 하고 분위기있는 인테리어로 창 전면 바형식으로 되어있고 확트인뷰 가 분위기를 살려주는  독립적인 공간<br><br>합리적 금액 으로 주최하시는 행사 성격에 맞게 최대한 협조하여 만족스러운 행사진행 될수 있도록 최선을 다하겠습니다.<br><br>감사합니다~ *^.^*<br><br>',60000,50,'서울 강서구 허준로 198','가양프라자 2층 203호','05041380826','카페,생일파티공간대여,펍,소규모음악회,강서구,세미나,프로포즈','Y',217,37.5612789803203,126.860333226544,0,24,10,2);
--행 16
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'푸른나무 피아노연습실','강서구 우장산역 덕원예꼬 앞 피아노, 악기연습실','강서구 우장산역 덕원예고 앞에 위치하고 있는 음악학원입니다!<br><br>피아노.악기. 보컬 연습실 대여합니다.<br><br>주차 가능합니다!',7000,4,'서울 강서구 강서로45길 118','2층 푸른나무음악학원','05043220950','피아노연습실,음악연습실,발산동연습실','Y',68,37.5504094695448,126.831745238897,0,24,11,4);
--행 17
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'더블디컴퍼니 연습실','화곡 가성비 갑! 깔끔한 단독홀 더블디컴퍼니','화곡역 8번출구 도보 8분!<br><br><br><br>안녕하세요 더블디컴퍼니 입니다<br>20평 단독홀에 깔끔한 그레이톤의 댄스연습실입니다<br>블루투스스피커,와이파이 구비하고있으며<br>스탠드조명 필요시 의뢰하시면 대여가능합니다<br>화곡역 도보8분으로 역세권에 위치하고있는<br> 장점이 있는 홀입니다<br>%연습실 홀 스피커 볼륨은 12이하로 부탁드립니다<br>(주택가라 잦은민원발생-충분히 연습가능한 볼륨입니다)',5000,10,'서울 강서구 화곡동 1035-23','지하1층 B101호-102호','05041380365','화곡역연습실,댄스연습실','Y',89,37.5431093017804,126.836678212765,6,24,12,4);
--행 18
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'어썸뮤직(Awesome Music)','앨범제작, 개인소장음원 스튜디오 녹음실 및 연습실','안녕하세요! 염창동에 위치한 녹음실 "어썸뮤직"입니다<br><br>이곳은 맥시멈퀄리티의 엔지니어가 직접 운영하고 있으며<br>레코딩을 기본으로 믹싱 마스터링과 앨범 발매, 제작 CD, USB, 메모리카드 제작까지 도와드리고 있습니다.<br><br>※ 앨범, 커버, 광고, 나레이션, 성우 녹음 등 레코딩 작업을 하실 수 있습니다.<br>※ 12년 이상 경력자의 도움으로 안정적인 레코딩을 도와드립니다.<br>※엔지니어링 및 앨범 제작, 발매 등은 따로 문의 하시면 친절히 상담해 드립니다.<br><br>자세한 사항은 전화문의 바랍니다^^',40000,5,'서울 강서구 양천로67길 96-20','지층 녹음실','05043220708','녹음실,스튜디오,앨범제작,보컬연습실,작업실,레코딩','Y',51,37.5548729439057,126.870247768678,10,22,13,4);
--행 19
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'파리의 부엌 베이킹스튜디오','전문적인 장비가 갖추어진 베이킹공방입니다.','안녕하세요. 프로처럼 베이킹을 할 수있는<br>베이킹 공방을 대여합니다.<br>최대 4인까지 사용가능합니다.<br>마곡나루역(9호선,공항철도)도보10분입니다.',24200,4,'서울 강서구 마곡중앙로 161-22','210호','05041380274','베이킹공방,공유주방,베이킹스튜디오,공방대여','Y',103,37.5686323191248,126.825676720295,8,21,15,5);
--행 20
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'파티시즌, 강서파티룸','파티시즌, 파티룸/촬영/브라이덜샤워/이벤트 모임공간','모임이 즐거운 넓고 쾌적한 공간, 파티시즌 🌿<br><br>파티룸, 촬영, 생일, 디너모임, 우정모임, 크리스마스, 연말모임 등 모임 공간으로 추천 드립니다 :)<br><br>★ 생활방역 : 실내.외 올바른 마스크 착용, 손 씻기, 환기<br>★ 안전을 위해 매일 꼼꼼한 방역 소독하고 있어요~<br><br>☀️ 낮엔 채광 좋고 🌙 밤엔 무드있는 넓~직한 파티룸 !<br><br>화곡역에서 도보로 7분 거리에 위치한 27평 2층 전체<br><br>유럽형 모던 주방, 넓은 분위기있는 원목 바 테이블과 예쁜 우드 조명<br><br>영화감상, 온라인 콘서트, 음약 감상이 가능한 아늑하고 단아한 아름다움이 있는 다용도 공간<br><br>촬영용 고품질 시네로이드 LED 조명이 구비된 튜디오 촬영 공간에서의 다양한 포토 촬영까지 !<br>초록이 크로마키(중/대)와, 홀로그램 반짝이 천,  이벤트 촬영 소품들도 다양하게 구비되어 있어요.<br><br>이용 문의는 언제든 카톡 플친 상담 가능합니다!! @파티시즌<br><br>** 기본 최대 10인까지 이용 가능 ',20000,10,'서울 강서구 초록마을로4길 1','2층 파티시즌','05043220761','강서구파티룸,생일파티,이벤트,넓은파티룸,피로연','Y',154,37.5442297741132,126.845784849509,8,24,16,1);
--행 21
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'파티룸 렌탈스튜디오 달달','프라이빗하고 편안한 공간에서 우리끼리 자유롭게!!','파티도 하고 음식도 먹고 싶은데 마땅한 곳이 없는 분들!<br><br>소규모 인원들을 대상으로 강의를 진행하고 싶은데 비싼 대관료로 고민하는 분들!<br><br>동호회 모임 하고 싶은데 사람 많고 시끄러운 카페가 부담스러운 분들!<br><br>에어컨 빵빵하고 다른 팀 없이 우리끼리 즐겁게 즐기고 싶은 분들은 어서 오세요~!',33000,8,'서울 강서구 곰달래로 159','2층 렌탈스튜디오 달달','05043220925','파티룸,스터디룸,회의,모임,프로젝터','Y',78,37.5309554388702,126.850764723035,0,24,17,1);
--행 22
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'멜로디필라테스','마곡역 도보 1분 예쁜 프라이빗 필라테스 스튜디오','**예약 3시간 전까지 다른 시간대로 변경가능할 수도 있어요 비어있다면요! 시간 변경은 아래의 번호로 연락주셔요.(환불X)<br><br>1. 마곡역 도보 1분거리 초역세권<br>2. 스튜디오 전체 단독사용<br>3. 필라테스기구계의 샤넬이라 불리는 프리미엄 기구 폰브코랄핑크 색상으로 비치- 사진/영상찍기 굳💕<br>4. 기존에 대관하셨던 분들 지속적으로 사용하신답니다<br>5. 대관 사용인원 2인이상 시 5,000씩 추가됩니다.<br>6. 센터 수업시간 제외 후 대관가능합니다^^ 보통 평일 저녁(화목)은 수업이 차 있을 경우가 많아요~<br>7. 주차 1시간무료(초과시 본인부담)<br><br>더 궁금하신 내용은 문의주시면 안내드립니다 😃',15000,3,'서울 강서구 마곡중앙4로 10','그랑트윈타워a동 219호','05041380781','필라테스,운동시설,마곡','Y',93,37.5586662591433,126.828031409569,0,24,19,7);
--행 23
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'오유 필라테스 스튜디오','Only U, 당신만을 위한 프라이빗한 공간','1:1 개인 맞춤 기구필라테스를 위한 공간입니다.<br>개인수업 진행하시는 강사님들, 강사 준비 중인 수강생 분들을 위해<br>오전&amp;낮 시간 위주로 공간 open해드립니다.',15000,2,'서울 강서구 마곡동로10길 46','보타닉 파크 프라자 508호','05041380687','운동시설,필라테스,프라이빗필라테스','Y',107,37.5669922164055,126.839778443909,6,18,20,7);
--행 24
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'치유 필라테스','깨끗하고 프라이빗한 센터','1:1, 2:1 개인 및 듀엣샵입니다^^<br>마곡나루역 부근이며 저렴하게 대관가능합니다.<br>문의주세요^^',20000,3,'서울 강서구 마곡중앙5로1길 21','N동 204호 치유필라테스','05043220728','운동시설,필라테스','Y',89,37.5688830786157,126.826174187503,0,24,22,7);
--행 25
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'강서구 모임공간 다비드727','13평 단독 모임공간','강서구 모임공간 ''다비드727''입니다. ^^<br>* 실시간 스케쥴 : 홈페이지 확인 https://david727.modoo.at/<br><br>- 13평 단독대관<br>- 최소 1명 ~ 최대 6인까지 사용 가능  <br>- 예약팀당 주차권 1대 제공(최대 2시간까지) <br>- 독서모임, 스터디모임, 취업스터디, 면접준비, 원데이클래스, 회의실, 소모임, 워크숍, 소규모 세미나, 수업, 단독룸, 미팅룸 등   <br>- 사용 특혜 :  모임공간 존 외에도,  사진 및 영상촬영 공간으로도 활용되고 있는 트렌디한 컨셉존들이 있어요~ <br>                         촬영용 공간존도 사용가능하니  이쁜 추억 사진도 많이 남겨보세요 ^^<br><br>',20000,6,'서울 강서구 등촌동 14-7','727호','05043220965','스터디룸,소모임,독서모임,원데이클래스,취업스터디','Y',61,37.564241641442,126.848080909218,6,24,23,8);
--행 26
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'다이브스페이스 모임공간파티','모임이 즐거워지는 공간 다이브스페이스','무인으로 운영되는 곳이라 이용 후 정리정돈 부탁드려요<br><br>■ 회의, 수업, 스터디, 시험, 영상시청, 워크샵 등 모임을 위한 공간<br>■ 배달/포장 음식, 주류 이용 가능합니다.(국물 x,이용 후 환기 필수)<br>■ 주차가능 (2시간 무료, 추가시 옵션 1시간 1000원)<br>■ 입실 및 이용 안내문자 이용전 발송<br><br>추가주차 시간 필요시 옵션선택후 요청사항에 추가시간 적어주세요<br><br>*당일 및 전일 예약은 문의주세요<br>',2000,12,'서울 강서구 마곡서로 152','A1214호','05043220488','세미나실,스터디룸','Y',190,37.5677827750351,126.8254353376,0,24,24,8);
--행 27
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'요고조고','마을 안에서 소통하고 힐링을 나누는 공간','마을안에서 프리마켓과 마을굿즈상품을 만들고 다양한 프로그램으로 아이들과 성인수업을 하고 있습니다. <br><br>회의, 스터디, 강좌, 원데이클레스, 독서모임 등 가능<br><br>* 스터디룸/ 동아리룸 <br>- 5인 이상 / 5인 이하 <br>',20000,10,'서울 강서구 초록마을로 4','2층','05043220325','회의실,마을공간,화곡본동,스터디룸','Y',87,37.5450123805863,126.844821398857,10,22,25,9);
--행 28
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'Growth홀','회의, 세미나, 교육, 워크숍에 필요한 최적의 환경 제공','1. Growth Hall, Change Hall 은 교육, 세미나, 워크숍, 미팅을 위해 2020년 새롭게 오픈한 최신교육장입니다.  <br>2. 편안하고 쾌적한 인테리어로 강사와 교육생 모두 최적의 교육진행(행사, 모임)과 힐링의 시간이 가능합니다.  <br>3. 넓고 편리한 주차장 이용이 가능하며, 9호선 양천향교역과 연결된 건물(대방디엠시티)로 교통이용이 용이합니다. <br>4. 교육,워크숍, 미팅에 필요한 최신기능의 빔, 스크린, 마이크, 스피커가 마련되어 있습니다.<br>5. Growth 홀과 Change홀 동시 대관시 20% 대관비를 할인합니다. <br>6. 케이터링에 필요한 집기 (접시, 쟁반, 컵 등)가 다양하게 구비되어 있습니다.  <br>7. 도보 5분거리에 위치한 서울식물원 내.외부 산책이 가능합니다. <br>8. 마곡신도시의 맛집과 생활시설 이용이 편리합니다.<br>9. 교육장 이용시 센터 상주 직원에게 대관에 필요한 서비스 요청이 가능합니다.<br>10. 테이블 레이아웃을 변경할 수 있습니다.<br>',50000,30,'서울 강서구 양천로 344','마곡대방디엠시티 1차 B동 202호','05041381221','회의실,교육장,세미나실','Y',245,37.5681983241857,126.84053708028,7,22,27,9);
--행 29
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'와글로 스튜디오','15초 역세권 화이트 & 3컨셉 전체공간 단독이용!','■ 프라이빗 단독룸 내 3가지 컨셉존 구성!<br>화이트 톤으로 깔끔하게 정돈되어 어떤 컨셉의 촬영에서도 자연스러운 분위기를 만들어냅니다. 상품촬영, 스터디모임 등 원하는 목적으로 사용할 수 있어요. 프라이빗한 단독룸에 컨셉이 각각 다른 촬영 존이 있으니 다양하게 연출해보세요!<br>A. 윈도우존 - [블루&amp;화이트] 모던하고 차분한 분위기, 윈도우시트(창가벤치) 구성<br>B. 캠핑존 - [브라운&amp;베이지] 캠핑 컨셉, 미니 잔디밭 구성<br>C. 우드존 - [우드&amp;화이트] 우드 색감으로 아늑한 분위기<br><br>■ 무료주차OK! 대중교통YES! 대형마트 1분거리!<br>-&lt;와글로 스튜디오&gt;는 방화역 3번출구 도보 15초 거리에 위치한 렌탈 스튜디오 &amp; 파티룸 입니다<br>-충분한 주차 공간(무료) 시간제한없이 이용, 지하철역 15초거리로 대중교통 이용도 편리합니다<br>-대형마트(다이소 입점)도 1분거리에 있어 쉽게 이용할 수 있습니다<br><br>향기로운💕 공간으로 놀러오세요~<br>카카오톡 채널 @와글로 👀',8500,10,'서울 강서구 금낭화로 135','320호 (금강프라자)','05041380037','촬영스튜디오,렌탈스튜디오,쇼핑몰촬영,유튜브촬영','Y',213,37.5773651714906,126.812431028644,0,24,29,10);
--행 30
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'바이윤 (55평)','조리가능한 주방과 거실/침실 등 다목적 촬영가능','안녕하세요 바이윤 스튜디오 입니다.<br>크리스마스 컨셉 업데이트 되었습니다 <br>(무인, 단독, 최대 30명, 추가요금 無)<br><br>▶ 공간 및 촬영 레퍼런스<br>https://www.instagram.com/byyoon_studio<br><br>▶ 컨셉 : 화이트톤의 넓은 55평 다목적 섹션<br><br>① 주방 : 화이트&amp;우드 컨셉의 싱크대를 메인으로 3미터의 넓은 아일랜드 조리대에 싱크대 냉온수, 배수 가능합니다. <br> 3구 하이라이트, 냉장고, 전자렌지 그리고 주방용품들이 준비되어 있습니다.8인용 식탁에서 조리&amp;식사 촬영 가능합니다.<br><br>② 침실 : 모던하고 컨셉 변경 가능한 핑크/그레이 톤의 침실<br>③ 거실 : 옐로&amp;블루의 감각적인 컨셉으로 3인/2인/1인 소파 및 테이블<br>④ 호리존 : 새비지 2.7m 슈퍼화이트 롤<br>⑤ 단독 메이크업 대기실 &amp; 내부에 분리된 깨끗한 남녀 화장실 <br><br>※ KT 1기가 인터넷 전용선으로 쾌적한 라이브',35000,30,'서울 강서구 가양동 1467','중앙하이츠 아파트 상가동 B1F (핑크색 문)','05043220880','촬영스튜디오,무료주차,동시촬영가능','Y',512,37.5696462173054,126.84874910114,0,24,31,10);
--행 31
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'스튜디오 얼리샤인','유튜브, 인터뷰, 강의 촬영 등 기획에 맞게 세팅 가능한 공간','Croom은 유튜브, 인터뷰, 강의 촬영 등 기획에 맞게 세팅하여 촬영 가능합니다.<br>조형물 이동 가능하도록 바퀴 달려있으며, 디스플레이 박스 등 예쁘게 세팅하여 촬영해보세요!<br><br>7층 전체를 스튜디오로 이용하고 있기 때문에 전체 대관도 가능합니다. (사무실공간 제외)<br><br>궁금하신 부분은 문의 부탁드리겠습니다 :)<br>감사합니다.',44000,15,'서울 강서구 화곡로 330','삼보프라자 7층 스튜디오 얼리샤인','05041380085','촬영스튜디오,자연광스튜디오,리빙스튜디오,침구렌탈스튜디오','Y',245,37.5532354649144,126.851221084371,0,24,2,10);
--행 32
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'모임공간 벨로캉','모임공간, 크리스마스, 송년회, 빔프로젝터','실평수25평 공간 전체를 대여하여 단독으로 사용합니다.<br>내부에서  한쪽 공간은 편안한 쇼파가 놓여져 거실 처럼 구성되어 있는  공간<br>6인용 테이블 2개로 14명이 파티용 식탁을 동시에 사용할 수 있는 공간 <br>빔프로젝트로 영화, 스포츠경기를 관람할 만한 공간 등으로 구분되어 있습니다. <br>- 기준인원은 12명이나 인원 추가 시 최대 25명까지 사용 가능 합니다. <br>모르는 사람들 방해 없이 친구, 동료끼리만 사용할 수 있는 공간입니다.  <br> <br>※당일사용. 다음날사용은 (시스템으로는 안됨) 전화로 문의주세요',10000,25,'서울특별시 구로구 고척동 193-4','B101호','05040905313','파티룸,빔프로젝트,프로젝터,송년회,모임공간,크리스마스','Y',311,37.5055760696134,126.859642551439,0,24,2,1);
--행 33
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'구로 올스페이스 파티 렌탈스튜디오','가족모임, 요리, 소규모 행사에 최적화된 파티룸','세련되게 리모델링된 주방과 거실의 다이닝 테이블에서 최대 8명이 이용가능하며<br>소규모 모임 및 가족모임, 돌잔치, 브라이덜샤워, 생일, 프로포즈, 렌탈스튜디오, 워크샵, 회식, 회의실등으로 이용하실 수 있어요.<br>120인치 프로젝터 및 50인치 QLED TV, 5.1ch 550w JBL 스피커를 갖춰 생생한 음악감상과 영상시청이 가능합니다.<br>',20000,8,'서울 구로구 구로동 650-4','SK허브수 A1528','05043220968','파티룸,가족모임,빔프로젝트,영화감상,돌잔치','Y',413,37.4960263199814,126.872356881262,0,24,3,1);
--행 34
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'무계획[신도림]','무계획 지하공간','&lt;공간소개&gt;<br><br>신도림역 부근 에 위치한 다목적 지하공간입니다.<br><br>무계획 공간은 소모임, 촬영스튜디오, 파티룸, 작업실, 영상 시청 등 다양한 용도로 사용 가능합니다.<br><br>천장 조명은 PHILIPS HUE로 세밀하게 색상과 밝기 조절이 가능합니다.<br><br>주변에 다양한 먹거리와 편의시설 그리고 공원이 위치해 편하게 이용 가능합니다.<br><br>예약 전날 저녁에 안내문자 발송해 드립니다. 원하시는 시간에 자유롭게 입실과 퇴실 가능합니다.<br><br>화장실은 1층에 위치해 있습니다.<br><br>이용시간 등 기타문의: 인스타그램(no_plan_space)',10000,10,'서울 구로구 새말로16길 21','지하1층','05041381662','파티룸,빔프로젝터,촬영,신도림,아늑한','Y',278,37.5046922452992,126.890839083584,0,24,4,1);
--행 35
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'로스터리카페 순','블랙톤에 깔끔하고 모던하고 옥상엔 루프탑 이용가능','전체적으로 블랙에 곳곳에 소소한 소품들이 있고, 특히 밤에 루프탑이 분위기가 좋습니다.',50000,20,'서울 구로구 고척로40길 3-1','로스터리 카페 순','05041380345','카페,루프탑,블랙,전망좋은카페,조용한','Y',531,37.5030676108818,126.851128430243,10,22,5,2);
--행 36
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[구로 휴플레이스] 카페 서우','빈티지 원목 인테리어에 따뜻하고 고급스러운 카페','빈티지 스타일의 구조에 테이블을 비롯한 전체 인테리어가 원목으로 되어 있고  전면 통 유리를 통해 흐르는 빛과 나무와 화초의 푸르름, 사진과 그림들이 어우러져 따뜻하고 고급스러운 느낌의 카페입니다.<br><br>구로시장 버스정류장 50m, 남구로역 4분 거리 대로변에 위치해 교통이 매우 편리합니다.<br><br>35평 규모에 창가 원목 라운드테이블과 13개의 원목테이블, 34개의 의자가  여유롭게 배치, 필요한 경우 확장가능하며 행사 성격에 따라 다양하게 공간을 배치 활용할 수 있습니다.<br><br>현재 공공도서관에서 운영하는 강사 초청 세미나와 교회 청년회 모임으로 대관이 이루어지고 있으며, 워크숍, 송년회, 파티 등 각종 모임은 물론 스튜디오 용도의 사진 및 영상 촬영 장소로도 아주 적합한 공간입니다.',80000,34,'서울 구로구 구로동로17길 2 ','3층','05041380823','카페대관,세미나워크숍,송년회파티,스튜디오촬영,분위기있는','Y',611,37.4884228674305,126.884307406684,0,24,6,2);
--행 37
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[구디] 칸태움 극장','구디/소규모공연장/기업PT/공연/촬영/스트리밍','구로디지털단지역 도보 7분 거리에 위치한 칸태움 극장은 사내 PT 발표, 기업 행사, 소규모 콘서트, 밴드 공연이 가능한<br>소극장 형태의 공연장입니다.<br><br>190인치 대형 LED와 40인치 큐브 LED 및 빔프로젝터 활용가능하며, 유튜브/트위치 등 라이브 중계 가능합니다.<br>기본 60석이 준비되어있으며 추가 좌석가능하며,<br>조명 및 음향 오퍼가 필요한 공연의 경우 예약 전 꼭 문의 주시길 바랍니다.<br><br>✅여수 MBC ''트로트클라쓰'' 촬영<br>✅가수 박상철 ''버스 한 대'' 뮤비 촬영<br>✅가수 박서진 ''무시마라'' 뮤비 촬영<br>✅가수 박상철 &amp; 유튜버 대도서관 컨텐츠 촬영<br>✅가수 공소원 &amp; 유튜버 띠미 컨텐츠 촬영<br>✅가수 한이재 &amp; 유튜버 소근커플 컨텐츠 촬영<br><br>대관안내 확인 必 : https://bit.ly/3vhqEtG<br>※ 조명 및 음향 오퍼레이팅 및 장비 사용 문의는 유선이나 카카오톡 [@칸 스튜디오&amp;극장] 문의 必<br>※ 스페이스클라우드에서는 시간대관만 가능합니다. 7시간 이상의 전체대관은 문의주세요',90000,70,'서울 구로구 디지털로32가길 25','2층 칸태움극장','05043220843','공연장,공연,소극장,촬영,주차가능','Y',511,37.4822102439849,126.89884554983,10,21,7,3);
--행 38
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'신도림 연습실 [디보 스페이스]','2층에 위치한 쾌적한 연습실','*특별한 공간으로 나누어져 있어 다양하게 활용이 가능합   니다.<br><br>*지하가 아닌 2층에 위치하고 있어 쾌적합니다.<br><br>* 상담시간<br>- 매일 10:00 ~ 20:00 (전화 불가, 문자 문의)<br>   (0504-3220-4654)<br>   <br><br>* 코로나 대응<br>- 사적모임 제한 해제로 기존 4명에서 6명으로<br>    기본 수용 인원을 확장하였습니다.<br><br>* 장기 예약 할인<br>- 10만원 이상 결제시 10% 할인<br>- 문자문의<br>    (0504-3220-4654)<br><br>* 룸 구성<br>- 대형(15평) / 대기실 및 모니터링 구역<br><br>* 위치<br>- 신도림역 도보 7분거리<br>- 주차 1대 가능 (단, 차고지 협소로 인한 대형차량 불가) <br><br>영업시간 09 ~23',6000,6,'서울 구로구 공원로6나길 5-20','2층 디보 스페이스','05043220465','신도림무용실,연습실,레슨실,성악레슨실','Y',237,37.5043962321244,126.889832958412,9,23,8,4);
--행 39
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'램프 댄스연습실','구로디지털단지 최고의 댄스연습실~!','예쁜 연습실에서 춤연습, 노래연습, 연기연습 하세요~!~!',8000,7,'서울 구로구 디지털로35길 17','2층 램프댄스아카데미','05041380844','구디연습실,댄스연습실,연기연습실,단체연습,개인연습','Y',192,37.4869900960943,126.896252629981,9,17,9,4);
--행 40
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'SMC음악연습실 신도림역 54호점','신규오픈 SMC 음악연습실 신도림역 54호점입니다','신도림역점 2,3번출구에서 직진 도보 5분거리 먹자골목에 위치한 SMC 음악 연습실 신도림역 54호점 입니다 :)<br>2022년 4월 20일 오픈했으며<br>깔끔한 최신 방음 시설이 구비된 시간제 방 운영중입니다 (소리좋은 업라이트 피아노, 보면대, 전신거울, 간이의자, 티슈, 종이컵, 세정제<br>당일, 한주, 한달 예약도 가능하오니 많은 문의 부탁드립니다 :)<br>',7000,2,'서울 구로구 구로동 41-13','2층','05041380493','구로연습실,피아노연습실,업라이트피아노,보컬연습실','Y',234,37.5040783576323,126.891979416766,0,24,10,4);
--행 41
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'유니하니 쿠킹 스터디룸 파티룸','쿠킹 스터디 및 파티를 즐길 수 있는 다목적 공간','안녕하세요! 유니하니 입니다 :)<br>유니하니 쿠킹 스터디룸 공유주방 파티룸은 간단한 쿠킹과 스터디, 회의, 간단한 요리와 파티 모임까지 누구나 이용 가능한 다목적 공간입니다.<br><br>2,7호선 대림역 근처에 위치하고 있어 찾아오시기 매우 편리합니다.<br>근처 편의점 및 카페가 있어 장 보시기에도 좋습니다.<br>주변에 다양한 먹거리 시설과 공원이 위치해 편하게 이용가능합니다.<br>기본적인 조리 도구와 양념이 있고, 여유 있는 식사를 즐길 수 있습니다.<br>스터디와 회의도 가능하며, 유튜브 등 촬영으로 사용하실 수 있습니다.<br>조용한 공간에서 특별한 시간을 보내보아요!<br><br>※ 다음 타임 예약이 없을 시 추가 연장 가능하지만, 시간을 넉넉하게 예약해주세요.<br>※ 현금 결제는 문의바랍니다.',7700,4,'서울 구로구 가마산로 271','구로오네뜨시티 908호','05043220548','공유주방,파티룸,쿠킹,모임,베이킹','Y',156,37.4963913837508,126.890463854012,8,23,11,5);
--행 42
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'유니하니 베이킹 파티룸 2호','베이킹 쿠킹 및 파티를 즐길 수 있는 다목적 공간','안녕하세요! 유니하니 구로대림점 입니다 :)<br>유니하니는 베이킹, 쿠킹 및 파티룸까지 누구나 이용 가능한 공간입니다.<br><br>2,7호선 대림역 근처에 있어 찾아오시기 매우 편리합니다.<br>근처에 마트와 편의점, 카페 등이 있어 장 보시기에도 좋습니다.<br>기본적인 조리 도구와 재료가 있어 베이킹 또는 식사를 즐길 수 있습니다.<br>베이킹 원데이클래스나 유튜브 촬영으로 사용하실 수 있습니다.<br><br>베이킹과 요리, 파티가 가능한 공간에서 특별한 시간을 보내보아요!<br><br>※주차는 근처 공영주차장을 이용해주세요.<br>구로근린공원지하공영주차장 : 30분당 900원<br>동구로공영주차장(하이그린파킹구로점) : 5분당 320원<br><br>',10000,8,'서울 구로구 가마산로26길 19','1층 유니하니','05041381336','공유주방,베이킹,쿠킹,유니하니','Y',171,37.4954304117204,126.891386881358,6,23,12,5);
--행 43
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'고척스카이돔 몬스터피자','최고급 음향, 조명시설의 120평규모 파티 라운지','Monster Pizza &amp; Pub<br>ㅡ<br><br>구로 고척동에 위치한 넥센 히어로즈의 홈 구장 <br>고척스카이돔에 와보셨나요? 다양한 경기, 공연, 행사가 벌어집니다. <br><br>몬스터피자&amp;펍은 고척스카이돔 지하1층에 위치했으며, <br>최고의 음향과 조명시설을 갖춘 120평규모의 라운지 공간입니다.<br><br>각종 공연 및 기획 파티, 연말모임 등이 가능합니다.<br><br>공연 할 수 있는 무대와 넓은 테이블, 의자는 물론<br>맛있는 음료/주류, 안주도 원하시면 준비해드립니다.<br><br>다트게임, 당구대 등 게임시설도 있습니다.<br>통대관으로 프라이빗한 모임/파티를 즐겨보세요 :-)</p>',100000,200,'서울특별시 구로구 경인로 430','고척동 고척스카이돔 B1 스카이워크몰','05040905038','파티룸,펍,무대,맥주,피자,초대형','Y',415,37.4980435680986,126.867355020286,9,21,13,1);
--행 44
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'서울스포트리','운동공간과 연습실이 한곳에서 이루어 지는 곳!','연습실은 요가실 및 플라잉요가, 댄스 연습실이 가능하며, 거울 및, 스피커까지 설치되어 있습니다.<br>운동시설은 풋살장으로 성인 풋살 대관 , 유소년 풋살 도 가능합니다.<br>아이들이 안전하고 즐겁게 운동할 수 있도록 안전에 신경써서 인테리어 했으며, 요즘 미세먼지 및 코로나로 인하여 공기에 대해 많이들 걱정하시고 계신데 저희는 GPS공기이온화 장치를 설치하여 미세먼지 및 유기화합물질을 감소시켜 안전하게 운동 할 수 있도록 신경쓰고 있습니다.',45000,20,'서울 구로구 경인로 403','A동 5층 스포트리','05043220468','운동시설,연습실,플라잉요가,풋살','Y',379,37.4979477213921,126.864279238507,19,24,14,7);
--행 45
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[신도림역 파티룸]사랑방 노란참새','따뜻하고 아늑한 공간','신도림역 2분거리에 있는 파티룸입니다.<br><br>저희는 다양한 모임과 컨텐츠제작으로 모인 팀이며 공간대여를 운영하고 있습니다.<br>많은 분들과 소통하고 싶어요!!<br><br>또한 필요시 제과제빵, 음식, 음료 제공이 가능합니다<br>(유료협의 / 전문 파티쉐)<br><br>인스타 : 사랑방 노란참새',20000,10,'서울 구로구 새말로 102','신도림포스빌오피스텔 417호','05043220529','파티룸,아늑한,역세권,깨끗한,분위기','Y',511,37.5055014797111,126.891471253366,0,24,15,1);
--행 46
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'구로 스터디룸 한승공간','한승공간 스터디룸 24시간 독서실','구로동 197-10 이앤씨2차 1204호<br>구로디지털단지, 대림역(2,7호선), 남구로역(7호선)<br><br>시간단위: 인당 시간당 1500원<br>24시간/365일 이용가능<br>연중무휴<br><br>빠른 인터넷(랜선,와이파이), 정수기, 샤위실, CCTV, <br>구내식당(4900원), 인근에 수많은 식당과 이마트<br><br>독립된 방<br>공부하기 좋은 매우 조용한 환경<br>보안 좋음 (각방 번호키 설치, cctv)<br><br>총11개의 직영점 (국내 5위 규모)<br><br>더 많은 정보와 방사진은 홈페이지에서 보실 수 있습니다.',1500,1,'서울특별시 구로구 구로동 197-10','이앤씨2차 301호','05040905498','스터디룸,독서실,공부방,1인실','Y',141,37.4866428940249,126.893369839564,0,24,16,8);
--행 47
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'공간대여 천우 오디션 연습실','실제 오디션이  가능한 연습실과 스튜디오 공간','영화, 드라마 등 오디션을 실시할 수 있는 공간입니다. (대기공간 충분)<br>*그 외 각종 실기 연습 및 연습, 수련이 가능합니다.<br><br>*신도림역 3번출구 테크노마트 6층<br>*최대 30인 입실 가능한 강의실, 세미나실<br>*대형 오디션, 연습스튜디오 대여<br><br>#음향기기, 화이트보드, 강의대, 마이크, 보조테이블, 의자 등 필요한 물품 무료로 대여해 드립니다.<br>#모든 차량 주차3시간 무료 가능 (이용시간 2시간인 경우 2시간 무료/미리 차량대수를 말씀주셔야 합니다.^^)',50000,30,'서울 구로구 새말로 97','6층 천우그룹, 공간대여 천우','05043220158','오디션,오디션연습실,연기연습실,오디션장소','Y',423,37.5070004300443,126.890148639406,11,21,17,4);
--행 48
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'공간대여 천우 회의실 강의실','신도림역 3번출구연결 테크노마트6층 주차장 무료','신도림역 3번출구 테크노마트 6층<br>*최대 100인 입실 가능한 강의실, 세미나실<br>*대형 오디션, 연습스튜디오 대여<br><br>#음향기기, 화이트보드, 강의대, 마이크, 보조테이블, 의자 등 필요한 물품 무료로 대여해 드립니다.<br>#모든 차량 주차3시간 무료 가능 (이용시간 2시간인 경우 2시간 무료/미리 차량대수를 말씀주셔야 합니다.^^)',200000,100,'서울 구로구 새말로 97','6층 천우그룹, 공간대여 천우','05043220328','대형회의실,100인강의실,세미나공간','Y',290,37.5070004300445,126.890148639407,11,21,18,9);
--행 49
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'르호봇 구로디지털 비즈니스 센터','예약은 센터로 전화문의 먼저 꼭!! 부탁드립니다.','르호봇 구로디지털 비즈니스 센터는 지하철 2호선 구로디지털단지역 3번 출구와 남구로역 1번출구에서 도보로 이동가능 합니다.',33000,10,'서울특별시 구로구 디지털로 288','대륭포스트타워 1차 207호','05040905478','회의실,세미나,미팅룸,스터디,비즈니스,빔프로젝터','Y',311,37.4834978791511,126.895333155084,9,18,19,9);
--행 50
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'구로디지털 웍앤코 회의실','구로디지털단지, 최적의 미팅 및 회의실 공간 대관','WORK &amp;CO. 는 CO: 함께, WORK: 일하다, 라는 의미로 다양한 업종의 입주사들과 비즈니스 시설을 공유한다는 뜻으로 만들어진 브랜드 입니다.<br>WORK&amp;CO.는 구로디지털단지 內 최대 규모의 공유오피스로서 당신의 새로운 비즈니스 PATH가 성공적으로 시작될 수 있도록 좋은 협력자가 되겠습니다.',66000,12,'서울 구로구 디지털로34길 55','코오롱 싸이언스밸리 2차 B1 웍앤코','05041381526','회의실,공유오피스,웍앤코,미팅룸','Y',511,37.4844159563863,126.899424866448,9,18,20,9);
--행 51
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'연컴퍼니 스튜디오','사진/영상 이용 가능한 촬영 장비,키친 스튜디오','&lt;기본제공&gt;<br>- 테이블, 의자, 소품 등<br>- 핀 마이크 2개<br>- 스위처<br><br>&lt;추가 옵션&gt;<br>- 카메라 (추가 비용 +50,000원)<br>- 조명 (추가 비용 +20,000원)<br>-  PC (추가 비용 +5,000원)<br>- 촬영 매니저: 라이브커머스 진행 매니지먼트 (추가 비용 +100,000원)<br>- 모델/쇼호스트 섭외 (추가 비용 +150,000원 부터~)<br><br>수용인원: 최소 1명 ~ 최대 10명<br>이용 가능 시간: 09:00 ~ 22:00</p>',30000,10,'서울 구로구 디지털로32다길 52','2층','05043220957','촬영스튜디오,라이브커머스,녹음실,방음부스,셀프촬영,쿠킹스튜디오','Y',246,37.4808720151741,126.898576008069,9,22,21,10);
--행 52
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[신도림]기계공업사 스튜디오 공장','서울 신도림 근방 운영중인 공장이라 현장감 MAX','실제 운영 중인 공장이기에 자재들이 들어올 수 있습니다.<br>가벼운 자재의 경우 촬영에 방해되지 않게 치워드릴 순 있으나<br>무거운 자재의 경우 옮기기 불가능할 수 있습니다.<br>물론 그 자재 역시 미술로 이용하고 싶으시다면 파손되지 않는 선에서 가능합니다.<br>파손 시 변상의 책임은 예약자에게 있습니다.<br>예약 시 공장의 현재 상태 다시 공유해드리고 승낙하시면 진행하고 있습니다.<br>*사진 내부 자재 없는 경우 / 있는 경우 올려드리니 참고 부탁드립니다.<br><br> <br><br>공장 내부에 있는 간단한 공구들은 소품으로 사용하셔도 됩니다.<br>사용하셨다면 반드시 제자리에 두어야 하며 파손 시 변상의 책임은 예약자에게 있습니다.<br>공구 사용으로 다칠 실 경우 제공자에게는 책임이 없음을 알립니다.<br>안전에 신중하게 사용 부탁드리며 미리 협의 부탁드립니다.',50000,10,'서울 구로구 신도림동 439-17','광명기계공업사','05041380497','촬영스튜디오,공장로케,로케이션,서울,현장감,공장','Y',172,37.5059995846065,126.884656340769,0,24,22,10);
--행 53
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'렌탈스튜디오쏠라','자연 채광이 가득한 24시간무인 쏠라스튜디오 ','15평 단독 스튜디오!❤<br><br>홈페이지 스케줄 꼭 확인 후 예약 부탁드립니다 !<br>https://ssolla.modoo.at/<br><br>[구로 신도림 대림] 인근에있는 3층 통창으로 채광 가득한 자연광 무인렌탈스튜디오 쏠라 입니다.<br><br>3400m의 높은 층고로 <br>쇼핑몰,화보,유튜브,인터뷰,뷰티,소품촬영,만삭사진,아기사진촬영 등 다양한 사진 및 영상 촬영 가능합니다.<br><br>인원추가비용 없습니다<br><br>무료주차,엘리베이터 이용가능 합니다<br><br>깔끔한 실내 화장실이 있어 이용하기 편리합니다<br><br>여섯종류의 풀 사이즈 무선 전동 배경지 사용가능<br><br>지속광 순간관 무상대여가능<br><br>애견동반가능<br><br>🖤블로그,인스타그램,스마트스토어리뷰 작성시 1시간 서비스 드립니다^^🖤<br><br>합리적인 가격으로 좋은공간에서 이쁜촬영하세요',12000,7,'서울 구로구 공원로 26','금호아파트 상가동 414호','05041380119','촬영스튜디오,단독스튜디오,엘리베이터,주차가능,자연광','Y',249,37.4998707532026,126.892078777002,0,24,23,10);
--행 54
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'구로 넷마루 대형비디오월 뉴스룸 ','대형 비디오월과 서재가 한 공간에 있습니다.','대형 비디오월과  서재가 한 공간에 있는 다목적 스튜디오 입니다. 분리된 공간이 있어 대기실로도 사용이 가능합니다.<br><br>온라인과 오프라인을 한번에! <br>대형 다목적 스튜디오에서 원하시는 모든 촬영을 해보세요! <br><br>*스튜디오를 방문해주시는 모든 분들은 건강한 스튜디오 환경을 위해<br>스튜디오에 구비된 손소독제를 사용하고, 발열 체크 후 입장이 가능하시고<br>모든 방문자의 성함 및 연락처를 적어주셔야합니다.*<br><br>- 저희 스튜디오는 매일 1회 이상 소독을 진행하고 있습니다-',440000,50,'서울 구로구 디지털로33길 27','삼성 IT밸리 407호','05043220041','촬영스튜디오,뉴스,뉴스룸,대기실,대형스크린,라이브방송,다목적','Y',491,37.4860495042971,126.894792519819,0,24,24,10);
--행 55
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'생일파티는 Double.H','더욱 즐겁고 휴식이 될 수 있는 소통공간','Double.H는 신월동 시영아파트 내 시영 상가에 위치하고 있습니다. 화이트톤의 깔끔하고 환한 느낌의 인테리어로 스터디 공간이나 소모임. 친구. 연인과 잠시 들러 커피 한잔하기에 좋은 분위기의 공간입니다. <br><br>공간 배치가 잘 되어있어 이벤트 행사나 친구들과의 생일파티 장소로도 사용하실 수 있어요. 주차공간이 마련되어 있어 접근성도 좋은 공간입니다. 청결과 건강. 친절을 우선으로 하는 사장님이 직접 운영하는 공간이구요. 직접 만든 수제 베이커리. 쿠키. 청음료. 커피와 함께하는 여러분의 모임이 즐거워지기를 바랍니다.',80000,20,'서울특별시 양천구 신월동 987-1','시영상가 110호 Double.H','05040905627','카페,브런치모임,동호회모임,스터디','Y',178,37.5161717140706,126.835113751821,9,23,25,2);
--행 56
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'미미네','스폐셜한 조리기구로 독립적인 공간에서 즐겨보세요.','안녕하세요 미미네 입니다 :-)<br>공유주방 + 파티룸 개념 입니다.<br><br>바로 같은 상가에 작은 슈퍼가 있고, 도보 3분 거리에 편의점 있습니다.<br><br>좋은 장소 와 좋은 이야기들이 오고 갑니다.<br><br>매장내 와인을 판매 하고 있습니다. 저렴한 가격에 좋은 와인으로 구비 해놓았으니<br>구매 원하실 경우 말씀 부탁드려요.<br>',28000,13,'서울 양천구 목동서로 70','목동신시가지아파트 2단지 상가동 미미네10분요리','05041380797','공유주방,인덕션,파티룸,와인,넷플릭스','Y',361,37.5368004790921,126.878057814383,0,24,26,5);
--행 57
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'온하다 브라이덜샤워 생일 모임 파티룸','주방/실내화장실까지 준비된 30평 모임장소 파티룸','안녕하세요. 30평 단독룸 렌탈스튜디오 온하다 입니다.<br>#연말모임 #기념일이벤트 #공간대여 #워크숍 #데이트 #엠티 #가족모임 #회식 등 모두 가능합니다. <br><br>* 파티룸 / 주방 / 실내화장실<br>- 기준인원 : 4인 (추가 1인당 5000원)<br>- 24시간 운영<br><br>* 맞춤 파티룸 세팅<br>- 고객님 니즈에 맞춰 테이블 플라워세팅(색상조율가능) / 벽면 글자풍선 세팅이 가능<br><br>* 청소보증금 5만원 입금해야 최종 예약 확정<br>- 예약 결제 후, 계좌번호와 함께 문자안내 보내드립니다.<br><br>',30000,12,'서울 강서구 곰달래로60길 9','2층 스튜디오온하다','05043220767','파티룸,브라이덜샤워,데이트장소,생일파티','Y',294,37.5318220545477,126.863295809515,0,24,27,1);
--행 58
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[목동] 플랜비 스튜디오 파티룸','루프탑을 보유한 목동 스튜디오 & 파티룸 공간','오목교역 1분거리의 루프탑을 보유한 프라이빗 모임 공간입니다.<br>렌탈 스튜디오, 파티룸, 브라이덜샤워, 생일파티, 프로포즈 다양하게 이용하실 수 있어요^^<br><br>거실 공간 / 호리즌룸 / 샹들리에룸 / 계단 포토존 / 옥상 루프탑등 5층과 루프탑 공간 모두 독립적으로 이용가능합니다.<br><br>*공간에 대한 사진 정보는 인스타에서 확인하여 주세요! <br><br>https://www.instagram.com/p/CLQkgvJHnKR/?igshid=ujotzj8lxtf4<br><br>*주간 예약 및 스튜디오 촬영 문의 /  시간 단위 예약은 네이버에서 플랜비 스튜디오 N 파티룸을 검색하여 예약하여 주세요~!<br><br>*파티룸으로 이용시 이용료외에 청소보증금 5만원이 있으며, 예약 확정후 안내하여 드립니다<br>',25000,6,'서울 양천구 오목로 337-2','5층','05041381750','파티룸,루프탑,브라이덜샤워,생일파티,빔프로젝터','Y',427,37.5248704987599,126.87520380713,9,24,28,1);
--행 59
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'리모트 카페','목동에 위치한 예쁜 레트로 감성컨셉의 카페입니다.','레트로 감성 컨셉의 디저트 카페입니다. <br>잡지,sns,유튜브촬영,클래스등 편안하게 대관 예약 문의주세요 :)<br>방송국,단체 촬영팀은 따로 문의주시면 조금이라도 할인해드립니다!',15000,8,'서울 양천구 목동중앙본로7길 34','3층 리모트커피','05041380277','카페,레트로,유튜브촬영,로케이션','Y',234,37.5396377647154,126.866831603491,10,22,29,2);
--행 60
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'커피집,이공','2층 유리통창으로 나무가 보이는 넓은 카페입니다.','안녕하세요^^<br><br>''커피집,이공''은 동네 한가운데 있는 편안하고 조용한 공간을 만들고자 시작한 카페입니다.  카페는 2층이며, 큰 통창이 매력적인 약 20평 정도의 공간입니다. <br>전체적으로 우드톤이고 고요하고 잔잔한 인테리어를 지향합니다. <br><br>1. 5호선 목동역과 신정역 사이에 5분거리에 위치하여 교통이 편리하게 이용가능하신 공간입니다.<br><br>2. 내부 화장실이 마련되어 있어 위생적이고 편리하게 사용이 가능합니다.<br><br>3. 스터디모임, 클래스, 파티, 강연등의 다양한 모임이 가능합니다.(가구재배치 가능)<br><br>4. 최대 이용인원은 20명입니다.(10-15명정도의 인원을 권장합니다.)<br><br>5. 간단한 음식(디저트류)과 음료 반입가능합니다.(카페에서 주문도 가능합니다.)<br><br>6. 주류는 반입 불가입니다.<br><br>7.파티룸으로 예약시 청소보증금 5만원이 있습니다.(정리 확인 후 바로 입금해드립니다.)<br><br>8. 예약은 최소한 2일전에 부탁드립니다.(일요일은 예약 불가합니다.)<br><br>9. 주차는 따로 문의주세요.',30000,20,'서울 양천구 오목로 204','2층 커피집,이공','05041381525','카페,통창,모임,스튜디오,자연광,조용한','Y',371,37.5253806934394,126.860128671982,8,24,30,2);
--행 61
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'염창역 에이투나인 넓은 연습실 ','염창역 에이투나인 ATO9 연습실','@@@대관가능 스케줄및 당일 대관은 카톡이나 번호로 먼저 연락주시어 확인 한번 부탁드립니다^^@@@<br><br>에이투나인 연습실입니다^^<br>코로나를 위한 소독작업을 철저히 하고 있습니다<br><br>흡음 작업으로 울리지 않으면서 영상촬영 가능(오디션제출영상 최적화) <br><br>월정기대관 할인!<br>새벽대관 할인!<br>개별적으로 문의 부탁드립니다 <br><br>충격흡수 댄스플로어의 가로9m 세로 7.5m 의 넓은 공간<br>연습실 내 탈의실, 정기대관팀을 위한 적재공간, 발레바, 핸드폰 삼각대, 공기청정기, 요가매트, 테이블및 의자 기본보유  <br><br>*청결관리를 위해 연습화 구분없이 신고오신 외부신발을 신고 그대로 연습하시는 경우는 중도퇴실되며 추후예약도 안받고있습니다<br><br>6명부터는 시간당/명당 1일 2000원추가 (사전요청과 다른경우 과징금 청구)<br> <br>카톡문의  studioato9<br>https://studioato9.modo<br><br>주인장이 외부 작업시 답이 늦어질 수 있는 점 너그러히 양해 부탁드리고<br>최대한 빨리 답하겠습니다.',30000,20,'서울 양천구 목동 526-3','레코드 피자건물 지하 스튜디오 에이투나인','05041381705','댄스플로어연습실,연습실,발레,춤연습실','Y',194,37.5461129581508,126.874381947326,0,24,31,4);
--행 62
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'블루픽셀 스튜디오','까치산역 셀프 스튜디오 블루픽셀 입니다.','편안하고 감성 넘치는 공간에서 저렴한 가격으로 고퀄리티의 녹음과 촬영이 가능한 공간입니다.',20000,4,'서울 강서구 화곡동 904-3','305호 블루픽셀 스튜디오','05043220081','녹음실,보컬연습실,반려동물동반,레코딩','Y',125,37.5289671342247,126.847748026926,0,24,2,4);
--행 63
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'2324 records','합주,레슨,개인연습,데모녹음,영상촬영 등 가능','안녕하세요.  <br>저희 팀이 사용하는 작업실이 비어있는 시간이 많아<br>함께 쓰실 분들을 구하고 있습니다. <br><br>합주, 개인연습, 데모녹음,개인레슨, 영상촬영 등 <br>음악에 관련한 기본적인 활동은 모두 가능합니다. <br><br>그리고 독립되어 있는 프라이빗한 공간이라 간섭받지 않고 작업할 수 있으며, 분위기도 연습실의 느낌보다는 개인 작업실의 분위기로 편안합니다. <br><br>참고로 저희는 5인조 밴드 영상촬영용으로 사용하고 있습니다. <br><br>오목교역에서 걸어서 10분거리라 대중교통으로 오시기에 무리 없고, 주차장도 있어서 주차도 가능합니다. <br><br>보시고 편하게 문의 주세요. <br>감사합니다. <br><br>',5000,7,'서울 양천구 목동 923','지하3층','05043220855','합주실,레슨실,악기연습실,주차가능','Y',93,37.5279582256718,126.870594201373,0,24,2,4);
--행 64
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[목동] 마음가온 파티룸,공유주방','💓아늑한 우리들만의 공간에서 즐기는 파티💓','방역 대책에 따라  10인 이하, 24시까지  이용가능합니다.<br><br>어플 내 결제 외에 청소보증금 4만원이 아래계좌로 입금되어야 예약이 최종 확정됩니다.  <br>*기업은행, 321-070561-01-019, 이진숙(예금주)*<br><br>* HAPPY BIRTHDAY, BRIDAL SHOWER, I LOVE YOU 가랜드 필요시 문의주세요 (추가금 5,000원)<br><br>❓문의방법❓<br>* 카카오채널 ID 마음가온 <br>* 인스타그램 @maeum_gaon DM<br><br>&lt; 진행중인 이벤트 &gt;<br>💌이벤트 1. 1시간 서비스 ( 택1 )<br> 1. 스페이스클라우드 내 이용후기(사진+추천글)  &amp; 인스타 팔로우<br> 2. 마음가온 인스타에 등록될 사진 전송 ( 개인 인스타 계정 업뎃으로 변경 가능)<br><br>💌이벤트 2. 당일이용고객 아메리카노 1잔 무료 (5:30까지 주문가능)<br><br>💌이벤트 3. 1층 와인바숲 와인, 안주 10% 할인  <br>고급진 입맛의 사장님이 직접 셀렉한 좋은 와인과 맛있는 안주 <br>메뉴는 마음가온 블로그를 확인해주세요.',13000,10,'서울 양천구 목동동로10길 19','지층','05043220904','공유주방,파티룸,빔프로젝터,영화감상','Y',174,37.519370711877,126.871774156389,0,24,3,5);
--행 65
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'카페형 모임공간 비어 박스','신정 네거리역 4번출구 단체 행사라면!','40명 수용가능한 단체행사 공간입니다.<br>쾌적하고 깔끔한 인테리어를 자랑하는 공간입니다.<br>각종 행사 및 파티 진행이 가능합니다.',160000,40,'서울특별시 양천구 중앙로32길 1','2호','05040905467','파티룸,송년회,신년회,동호회,단체모임,카페','Y',245,37.518604951399,126.854366666727,9,21,4,1);
--행 66
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'반려견 문화공간 두스펫페','반려견을 사랑하는 사람들의 모임 공간','서울 목동에 소재한 반려견을 위한 프리미엄 복합공간(DOGPLEX)을 지향하는 두스펫페입니다. 행복하고 스마트한 견주님과 반려견 모두의 삶을 위해 다양한 라이프 스타일 서비스들을 제공해 드리고 있습니다. 반려견 동반이 가능한 공간을 대여하여,  원데이 클래스 , 반려견생일파티, 동호회 모임, 어질리티 모임 등 다양한 이벤트를 기획하실 수 있습니다.',40000,10,'서울특별시 양천구 신정동 1028-4 ','2층 두스펫페','05040905125','반려견동반,반려견파티,반려견모임,애견동반,파티룸','Y',431,37.5213352294771,126.856403207264,10,23,5,1);
--행 67
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'무브드포레','목동역 1분거리 역세권,통유리, 바닥난방시설완비','목동역 4번 출구 1분 거리에 있는 초역세권 무용학원입니다. 바닥은 탄성마루, 수입 댄스플로어로 시공되어있으며 바닥에 열선 시공되어있어 찬 바닥에서 스트레칭하지 않으셔도 됩니다. 천장형 냉난방기도 사용가능합니다. 전체 통유리로 나무가 보이는 뷰에, 큰 창으로 환기 가능합니다. 발레바 소도구 매트 구비되어있습니다. 상가 건물이라 층별로 화장실있고, 세면대와 탈의실 등 갖춰져있으며 20여평의 휴게실도 마련되어있습니다.',30000,3,'서울 양천구 목동로 212','A상가 3층','05043220464','발레,운동시설,무용,현대무용,홀대여','Y',155,37.5263855536734,126.866170731713,0,24,6,7);
--행 68
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'플랜A스터디카페 몰입아카데미센터','신월동 신정동 스터디룸 면접 과외 상담 회의 공간','안녕하세요. <br>플랜에이 스터디카페 몰입아카데미센터의 그룹스터디 공간을 소개합니다.<br><br>▶ 저희 센터는 양천구 신월동의 목동센트럴아이파크 위브 2단지 아파트 인근, 남부순환로 대로변에 위치한 몰입아카데미 빌딩 6층에 위치하고 있습니다.<br><br>▶ 2개의 스터디룸이 제공되며, 그룹스터디, 과외, 화상 면접, 온라인 시험, 상담, 회의 용도로 사용가능합니다.<br><br>▶ 사용 기본 요금은 1시간/1인 기준으로 2000원입니다. 추가 1시간 당 2,000원입니다.<br><br>▶ 영업 시간은 오전 08시부터 익일 02시까지이며, 휴무일은 없습니다.<br><br>▶ 빔프로젝터, 모니터는 마련되어 있지 않습니다.<br><br>▶ 별도의 주차공간은 없습니다.<br><br>감사합니다.<br>',7000,4,'서울 양천구 남부순환로 605','몰입아카데미 6층','05043220518','스터디룸,스터디카페,과외공간,프린터','Y',103,37.5150915237198,126.840777397592,8,24,7,8);
--행 69
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'리디아 그림책방','클래스, 책모임에 제격! 그림책 공간을 공유해요 ','중고 그림책 전문 서점, 리디아 그림책방입니다.<br><br>중고 그림책 판매 및 매입 / 독서 / 원데이 클래스 / 강연 / 책모임 등이 열리는 동네 서점입니다.<br>책 관련 모임이나 클래스 환영해요.<br>7평 규모로 소모임 하기에 적합합니다.<br>최대 10명 수용 가능해요.<br>책방 영업시간 외 시간에 공간 대여합니다.<br><br>빠른 문의는 영업시간 내 카카오톡채널 [리디아 그림책방] , 유선전화, 인스타그램 DM 가능해요.<br><br>양천구 목동14단지 B상가 201호 위치<br>(2호선 양천구청역 도보 10분, 5호선 오목교역 버스 10분)<br>상가내 화장실 이용 가능<br>외부 음식 반입 가능(쓰레기 수거 및 뒷정리 필수)',15000,10,'서울 양천구 목동동로 130','목동14단지 B상가 201호 리디아 그림책방','05043220156','스터디룸,책,클래스,책모임,소모임','Y',86,37.5144109696881,126.872031487291,10,22,8,8);
--행 70
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'어썸팩토리목동3플레이스','양천구에서 가장 공부가 잘되는 독서실, 어썸팩토리','안녕하세요 양천구에서 가장 공부가 잘되는 독서실, 어썸팩토리 목동3플레이스입니다.  <br><br>- 집중을 위한 편안한 공간<br>- 좀 더 공부하고 싶어지는 학습 공간<br>- 학습자들이 진정으로 원하는 학습 공간<br>- 카공족들을 위한, 조용한 분위기의 공간<br>- 휴식과 공부가 가능한 카페 공간 <br>- 선택의 폭이 넓은 기간권<br>- 다양한 음료 또한 제공해드립니다.<br><br> 학습자분들의 꿈은 어쌤팩토리 목동3플레이스에서 이루어집니다!  합리적인 가격의 프리미엄 독서실',4000,2,'서울 양천구 신월로38길 13','금왕빌딩 4층','05043220282','스터디룸,스터디카페,독서실','Y',77,37.5207735159953,126.861356150165,9,24,9,8);
--행 71
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'이서당하우스 회의실','전망 좋은 목동 회의실/밝고 깔끔한 스마트한 공간','서울 시내가 한  눈에 보이는 전망 좋은 회의실입니다. <br><br>- 양천구청역 10분 거리<br>-10인 정원의 회의, 스터디, 좌담회, 원데이클레스, 독서모임 등에 최적화된 공간 <br>- 화상회의 시설 구축. 좌담회 녹화, 강의 녹화 가능 ( 촬영 시 시간당 10,000원 추가 ) <br>- 대형 화이트보드 / 85인치 전자칠판 ( 전자교탁 내 최신형 PC 연결됨. 노트북, 패드 연결 가능 ) <br>- zoom, Youtube live 진행 가능 ( 시간당 10,000원 ) <br>- 최고급 퍼시스 테이블/의자/전원케이블<br>- 건물 지하 주차장 이용 가능. ( 3시간 무료 주차 )',20000,8,'서울 양천구 목동서로 349','14층 1413호 이서당하우스 ','05043220581','회의실,전자칠판,화상회의,빔프로젝터','Y',243,37.517399267113,126.865253576251,8,24,10,9);
--행 72
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[곰달래꿈마을] 회의 등 대여공간','마을을 위해 모인 주민공동체, 곰달래꿈마을','주민을 위한 마을을 만들기 위해 주민들이 직접 발벗고 나서서 만든 주민공동체 곰달래꿈마을입니다. <br><br>지역 주민들을 위한 커뮤니티 공간과 다양한 프로그램을 지원합니다. <br><br>누구나 사용 가능한 공간이니 편하게 문의주세요.<br><br>메일 : rhaekffo7@naver.com<br><br>',80000,40,'서울 양천구 곰달래로 36','곰달래꿈마을','05043220778','회의실,강의실,빔프로젝터,세미나실,방음시설','Y',176,37.529767880354,126.836772358953,9,22,11,9);
--행 73
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'목동맨션','[목동] 채광이 좋은 디자이너의 공간/목동맨션','안녕하세요. 목동맨션 스튜디오입니다.<br>디자이너가 실제 사용하던 공간으로, 구옥 1층과 2층을 스튜디오로 개방하였습니다. <br>목동맨션에서 편안하고 즐겁게 촬영해주세요!<br><br>1호점: 목동중앙남로 83, 1F<br>2호점: 목동중앙남로 83, 2F<br><br>✔️스케줄 확인: https://url.kr/i2yzh1<br>📷인스타그램: @mokdong_mansion<br><br>[목동맨션 1호점: 1F 그녀의 작업실]<br>빨간 벽돌로 만들어진 돔형태의 매력적인 외관에 실제 디자이너가 작업하던 작업실 그대로 내추럴하게 살려두었습니다.<br>&nbsp;<br>[목동맨션 2호점: 2F 홈커밍]<br>작업실 바로 윗층, 그녀가 쉬는 공간으로 활용하던 곳을 개방합니다. 작업이 끝난 후 빨리 귀가하고 싶은 포근한 공간입니다.<br><br>',55000,10,'서울 양천구 목동중앙남로 83','1층,2층 목동맨션','05043220613','촬영스튜디오,자연광,쇼핑몰촬영,빈티지,유튜브촬영,반려동물동반가능','Y',136,37.5412214841688,126.8650353312,0,24,12,10);
--행 74
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'더 라운지 에이치','위스키와 음악이 있는 라운지 공간','고급 위스키 보틀과 대리석 마감이 모던함과 세련미를 더합니다.<br>음악 청취가 가능한 스피커 시스템과 82인치 스크린, 홈시어터가 완벽하게 구성되어 있는 라운지 공간입니다.',200000,10,'서울 강서구 월정로 136','4층','05043220024','촬영스튜디오,렌탈스튜디오,사운드시스템,넓은공간,모던한,라운지,고급스러운,위스키,홈시어터,루프탑,빔프로젝터','Y',479,37.5311658726329,126.837818653864,9,18,13,10);
--행 75
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'빈티지 오목 레트로 감성 와인바','레트로 스타일 편안한 감성 스페이스','현재 레트로 스타일의 와인바로 이용되어 있는 곳으로<br>전체 대관을 통하여 영상촬영 및 피팅 촬영으로 공간 활용 가능',100000,20,'서울 양천구 신정동 118-19','2층 빈티지바','05043220547','촬영스튜디오,반려동물동반가능,빔프로젝터,레트로,감성바,와인바,엔티크,카페','Y',377,37.5223816793226,126.875391778059,10,18,14,10);
--행 76
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'스튜디오 N','자연스러움과 따뜻한 홈 느낌의 공간 -스튜디오 N','자연스러움과 따뜻한 홈 느낌의 공간입니다. 자연광이 풍부하여 다양한 컬러와 독특한 소품으로 연출이 가능한 공간입니다. 자연광 렌탈 스튜디오로 채광이 좋고 가구들과 플랜테리어의 식물들이 어우러져 자연스러움과 따뜻한 홈 느낌을 연출해 줍니다.',40000,15,'서울 양천구 지양로 36','2F 스튜디오 N','05043220808','촬영스튜디오,렌탈스튜디오,자연광,유튜브촬영,쇼핑몰촬영,따뜻한,자연스러운','Y',235,37.5195857142553,126.836158246931,8,22,15,10);
--행 77
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[자연광]욕조컷 빈티지플랜트 목동','3면창 채광, 온수사용 욕조, 유튜브 및 방송촬영','인더스트리얼 빈티지'' 디자인의 감각적인 스튜디오!<br><br>***오픈이벤트 진행중***<br>참여방법 택1하여 조명장비 실속있게 이용하세요<br>#지속광, 순간광(시간당 5,500원) 무료이용<br><br>01 인스타 태그 달기<br>스튜디오에서 촬영한 사진 또는 영상을 #빈티지플랜트 #빈티지플랜트목동 #촬영스튜디오 태그와 함께 게시 or<br><br>02 스페이스클라우드 예약후 멋진 후기 남기기<br><br>#B section<br>마피아의 아지트가 상상되는 빈티지하고 거친 배경에 고급스런 오브제를 배치. 따뜻한 물이 나오는 욕조를 활용 유니크한 촬영 컨디션 제공. 3면이 창으로 이루어져 하루종일 자연광 만끽할 수 있습니다.<br><br>#A section<br>천장부터 내려오는 하얀천이 침대까지 이어져 몽환적인. 크고 작은 오브제들로 다양한 구도와 컨셉 연출 촬영. 호리존 역할의 하얀 벽면에서 깨끗한 촬영 가능합니다.<br><br>#스냅사진촬영, 프로필촬영, 의류촬영, 뮤직비디오촬영, 각종 사진 및 영상 촬영에 모두 추천해요 :)!',44000,40,'서울 강서구 화곡동 829-1','2층 빈티지플랜트 목동','05043220447','촬영스튜디오,자연광,컨셉스튜디오,욕조,빈티지,조명,스냅사진,의류촬영,뮤직비디오,반려동물동반가능','Y',199,37.5340528104153,126.858225852452,0,24,16,10);
--행 78
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'제3화원','식물과 햇볕으로 가득찬 제3화원','신월동에 위치한 카페 제3화원입니다 ',33000,20,'서울 양천구 남부순환로 402','4층 제3화원','05043220385','촬영스튜디오,자연광,빈티지,반려동물동반가능,음식물반입가능,화원,식물','Y',351,37.5315930234257,126.830808880514,0,24,17,10);
--행 79
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'목동파티룸 플레이파티룸','목동 최고의 파티룸입니다.','목동 각종파티,생일,브라이덜샤워,소모임,세미나,연말행사등 모임장소로 최고의 환경을 제공합니다.<br>코로나19관련 입실전 사용후 방역을 실시하오니 안심하고 사용하시기 바랍니다.<br>목동역8번출구에서 130m 1분거리입니다.',20000,8,'서울 양천구 오목로48길 1','지하','05041381238','파티룸,플레이파티룸,브라이덜샤워,생일잔치,송년회,보드게임,빔프로젝터','Y',222,37.5254764172379,126.863004772197,0,24,18,1);
--행 80
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'작심독서실 목1동점','마음먹음을 실천하는 공간, 작심독서실목1동점입니다','오래 앉아 있어도 허리에 좋은 시디즈 의자와 강의를 할 수 있는 화이트보드가 있고, 컴퓨터 스크린을 통하여 PPT도 가능합니다. <br><br>또한 공기청정기와 써큘레이터를 가동하여 학습에 쾌적한 환경을 조성해 드리고 있습니다.<br><br>주차권은 스터디룸 사용자를 대상으로 이용시간에 비례해서 1일 최대 3시간까지 발급해드립니다 (그 외 주차요금은 카드결제만 가능)',6000,4,'서울 양천구 목동서로 213','10층 작심독서실 목1동점','05041380582','스터디룸,컴퓨터스크린,회의실,빔프로젝터,화이트보드','Y',111,37.5279357006831,126.870594240285,9,24,19,8);
--행 81
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[당산]선유기지 파티룸 송년회 ','비밀스런 공간에서 즐기는 프라이빗 파티','<br>선유기지는<br>선유도역, 당산역 인근에 위치한 비밀기지 카페로서,<br>비밀스러운 곳에서의 낭만적인 파티공간을 제공합니다.<br><br>#크리스마스파티 #송년회 #망년회 #신년회<br><br>* 청소보증금 5만원 입금해야 예약확정!(설거지/분리수거/정리정돈 후에 퇴실 시 환급)<br>   예약결제 후에 계좌번호와 함께 안내 문자 보내드립니다.<br>* 낮 시간대 이용은 ''선유기지 카페대관''에서 예약해주세요<br>* 예약문의는 카카오채널 @선유기지 카톡 주세요',50000,16,'서울특별시 영등포구 선유로51길 1','1층 선유기지','05040905687','카페,프라이빗파티,파티룸,송년회,크리스마스파티','Y',861,37.5364924911849,126.89767194107,19,23,20,2);
--행 82
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[신규할인] 영등포시티뷰 여로','당신의 숨을 함께, 시티뷰 여로','바쁜 일상에 잠깐의 숨을,<br>당신의 쉼표로 함께합니다. 시티뷰 여로입니다.<br><br>영등포역 도보 3분, 타임스퀘어가 내려다보이는 16층입니다.<br>복잡한 도시에서 한 걸음 떨어져 고요를 만끽해보세요!<br><br>1층 현관을 나서기만 해도 먹자골목이 이어져있습니다.<br>배달음식이 지겹다면 먹자골목에서 흥청망청 놀아보시기!<br><br>간이주방과 세탁기는 물론,<br>4K 화질 지원 TV에는 넷플릭스/디즈니플러스/유튜브프리미엄 모두 이용가능!<br>샤워부스 설치된 깨끗한 화장실,<br>최대 10명이 둘러앉아 다과타임 가지기 넉넉한 테이블, 의자도 구비!<br><br>낮에는 쏟아지는 햇살을 맞으며, 촬영, 회의, 간단한 소모임을!<br>밤에는 감성 절정의 타임스퀘어 시티뷰를 감상하며, 와인 한잔의 여유를!<br><br>✔현재 포토이벤트를 시행하고 있습니다. 💕<br>-포토이벤트 참여 시 할인된다는 점 참고해주세요! <br><br>*카카오톡 @파티룸여로 <br>연락주셔요. 👀 ',15000,6,'서울 영등포구 영등포동3가 7','점프밀라노 1619호','05043220590','파티룸,브라이덜샤워,빔프로젝터,시티뷰,넷플릭스,디즈니,유튜브,대형티비','Y',763,37.5189073166578,126.90594792546,0,24,21,1);
--행 83
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[오픈할인] 영등포 루프탑 파티룸','영상 시설 완비, 소음 걱정 없는 [루프탑온에어]','영등포 루프탑 파티룸 :: 루프탑온에어<br><br>💛 실내 17평 / 루프탑 13평<br>💛 층 전체 단독 사용<br><br>▫️ 180인치 빔프로젝터🍿 고음질 스피커🎶<br>▫️ 보드게임🎲  미러볼🤹 블루투스 마이크🎤<br><br>📌 소음 걱정 없는 프라이빗 공간<br>📌 멋진 야경이 있는 루프탑은 덤!<br><br>✔️ 파티,연말,크리스마스,송년회,신년회,영상회,월드컵,콘서트,막춤파티,돼지파티,생일파티,덕질모임,유튜브,라이브,틱톡 촬영 등<br><br>낮에는 밝은 채광으로 환하게<br>밤에는 힙한 조명으로 힙하게<br><br>💚 다양한 쓰임이 어울리는 공간이에요. 어떻게 사용하든 자유입니다. 다만, 모든 굴레와 고민을 벗어던지는 공간이 되었으면 해요!<br><br>✔️ 조명이 많아요. 분위기 있는 사진, 영상 찍기 좋아요!<br>✔️ 빔프로젝터 : 넷플릭스, 유튜브, 디즈니, 와차, 웨이브 내장 및 HDMI, 미러링<br>✔️ 내부 화장실 ⭕️<br>✔️ 넓은 공영 주차장 2분 거리<br>✔️ 암막커튼 설치 완! 낮에도 빔 OK<br><br>✨ 문의 👉 카카오채널 @루프탑온에어',16900,11,'서울 영등포구 도신로 114','5층','05043220439','파티룸,빔프로젝터,크리스마스,신년회,올나잇,월드컵,생일파티,루프탑,반려동물동반가능,넷플릭스','Y',633,37.507918507667,126.904615805843,0,24,22,1);
--행 84
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'영등포 신길 몬타냐 카페 바 대관','신길동 카페 & 바 전체 대여','안녕하세요, 핸드드립 커피 &amp; 바 몬타냐 입니다.<br>조용한 동네 골목 안 위치한 카페 입니다.<br><br>기물 사용은 제한되나 특별한 경우 별도 협의 가능 합니다.<br>커피, 와인, 칵테일 등 클래스 및 사교 모임<br>',15000,5,'서울 영등포구 신길로45길 6','몬타냐','05041381452','카페,와인바,커피,칵테일,클래스,모임','Y',413,37.5093261315942,126.910110852177,0,24,23,2);
--행 85
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'TCC아트센터','서울시 영등포 당산동에 위치한 복합문화공간입니다.','TCC아트홀은 170석의 객석규모를 갖춘 극장으로 TCC아트센터 지하 1층에 위치하고 있습니다. <br>최신음향, 조명, 장비로 다양한 무대 연출이 가능하며 클래식음악회, 연극, 뮤지컬, 사인회, 발표회 등 공연에 손색없는 최적의 환경을 갖추었습니다. <br>고정식 객석이 아담한 분위기를 연출하며 무대와 객석의 거리가 가까워 출연자와 관람객이 긴밀하게 호흡할 수 있습니다. <br>또한, 최신식 극장답게 쾌적한 분장실과 대기실은 출연진과 제작진의 편의를 제공합니다.<br>TCC우석홀은 각종 발표회와 세미나, 회의, 리셉션 등 다양한 이벤트를 진행할 수 있는 첨단시설을 갖춘 다목적홀로써 TCC아트센터 지하1층에 위치하고 있습니다. <br>최대 100여명까지 수용 가능 하며, 행사규모에 따라 홀을 분리하여 활용 가능합니다.<br>그리고 전,후면 프로젝트와 노래방시설, 연회장으로 이용시 원탁과 다과 준비실 등 편의를 제공합니다.<br><br>TCC루프가든은 센터 6층에 있으며, 공연시 리셉션 장소로 활용 가능합니다.',500000,170,'서울특별시 영등포구 국회대로 539','TCC아트센터','05040905337','공연장,복합문화공간,소극장,연극,뮤지컬,음악회','Y',762,37.5293046227973,126.894952408134,9,22,2,3);
--행 86
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'철공소밑 팝업갤러리 주말극장 타래','댄스촬영부터 팝업스토어 플리마켓까지 다목적홀','힙력 절정 문래 창작촌 초입에 자리한 팝업스토어 (신흥상회 바로 옆)<br><br>전시, 연극/밴드 공연(49명 미만), 영상 촬영, 댄스촬영, 웨비나 플리마켓 등 공간에서 상상 가능한 모든게 가능합니다<br><br>철공소 영업이 끝난 평일 저녁, 주말 인근이 고요해 주차등의 편의 성이 좋습니다<br>* 철공소 영업시간인 평일 낮은 철공소 특성상 소음이 있습니다 (영상촬영 부적합)',130000,49,'서울 영등포구 문래동3가 54-34','지층','05043220265','공연장,연극,댄스촬영,팝업스토어,힙합,갤러리,철공소','Y',511,37.5139641165224,126.896438696039,0,24,25,3);
--행 87
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'문래역 다목적공간 스페이스 T','문래동에 위치한 다목적홀 소극장 입니다! ','문래동 로데오왁 상가 4층에 위치한 스페이스 T는 커뮤니티를 위한 다목적 공간으로 1)강연회, 토크쇼, 각종 회의,모임 등과 같은 행사와 2)소규모 연극공연, 어쿠스틱 음악회, 영상물 상연회 등, 작은 규모의 문화예술 행사 및 발표에 적합한 공간입니다.<br><br>스페이스T가 위치한 건물에는 병원, 상업시설 등, 여러 사업장이 함께 존재하므로 추가 앰프의 반입, 설치 혹은 관객의 함성과 같은 격한 반응을 유도하는 등, 큰 소리와 울림 등을 유발하는 행사는 적합하지 않을 수 있다는 점 미리 말씀드립니다.<br><br>덧붙여 코로나 예방 수칙 준수를 위한 안내사항을 꼭 참고 해 주세요. (위기 경보 격상 시 인원 제한, 사진파일 넘기면 있습니다) <br><br>실스케줄과 캘린더가 다를 수 있으니 이메일 혹은 전화 문의 주세요 ( asfcentre@gmail.com)<br><br>공간 상세 보기 : https://youtu.be/ET0Yeimw-s8https://youtu.be/ET0Yeimw-s8 (0:55'' ~)',50000,130,'서울특별시 영등포구 당산로 34','로데오왁 주차장건물 4층 403호 경계없는예술센터 - 스페이스 T','05040905029','공연장,극장,연습실,소극장,발표,강의,음향부스,다목적홀,음악회','Y',813,37.5175626983807,126.895387399506,9,23,26,3);
--행 88
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'당산예술공간 [영등포구청역점]','영등포구청역3분 역세권 프라이빗 대형 단독연습실','🏠당산예술공간(The artplace dangsan)<br><br> 업라이트 피아노🎹 <br>18평형 대형단독실 최고의 가성비 👍 <br><br>🚃[영등포구청역 2.5호선 도보3분이내 초역세권] <br><br>🚙서울 영등포구 당산로27길 20-3 지하1층<br>주차:불가 (도보3분 영등포구청 공영주차장 이용)<br><br>⏰️운영시간: 오전 8:00- 22:00까지 연중무휴<br>당일예약 전화주세요!!!!<br><br>👉👉👉카카오톡 문의<br>http://pf.kakao.com/_MPEHK<br><br>💥 드럼 연습실은 더이상 운영하지 않습니다.<br>다른공간을 이용해주세요!<br>',6000,3,'서울 영등포구 당산로27길 20-3','지하1층','05043220738','피아노연습실,레슨실,음악연습실,악기연습실,연기연습실,보컬연습실','Y',372,37.525418343906,126.894157477564,8,23,27,4);
--행 89
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'마하나임 뮤지컬','보컬 댄스 연기 연습이 가능한 공간입니다','저희는 뮤지컬을 주로 연습하고 배우는 공간입니다<br>뮤지컬을 연습하시고 싶은 개인 단체는 언제나 열려있으니 연락주세요..~<br>',9000,9,'서울 영등포구 신길동 425-8','207호 마하나임 뮤지컬','05041380253','뮤지컬,연습실,보컬,댄스,연기','Y',278,37.4996230891521,126.908199971525,0,24,28,4);
--행 90
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'바다요','한옥리모델링한 마당있는 공간','한옥리모델링한 공간으로 도심 한복판 마당 있는 100%예약과 대관인 프라이빗한 공간.<br>공유 주방을 사용함에 있어 대체적으로 모든 주방 집기(요리 도구, 그릇, 잔,수저 세트 외)와 조미료 등이  구비 되어있습니다. (단, 특이 메뉴 조미료는 직접 챙겨오시면 더 나을 듯 싶습니다.)',35000,6,'서울 영등포구 양평동1가 9-19','1층 바다요','05043220586','공유주방,한옥,마당,반려동물동반가능','Y',392,37.5214692586932,126.891190776635,0,24,29,5);
--행 91
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'꼰모베르스튜디오','유럽감성을 한스푼 담은 레몬컬러주방  ','실무에 필요한 베이킹 도구들과 넓은 작업대로  베이킹 연습,  원데이 클래스 혹은 플라워클래스 공간으로 적합하며 유럽감성을 담은 인테리어와 소품, 빔프로젝트 파티룸으로 사용이 가능하여요 <br>옆에서 케이크 매장운영중으로 케이크 주문시 할인적용',25000,4,'서울 영등포구 도신로15가길 11','1층, 꼰모베르케이크(스튜디오)','05041381559','공유주방,베이킹,원데이클래스,유럽감성,키친스튜디오','Y',478,37.5066350840615,126.89978808646,9,21,30,5);
--행 92
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'맛있는공간','영등포역 도보3분 주방컨셉 공유주방 파티룸','#1. 공간도 맛있다<br>- 공간의 디자인과 향 그리고 음식 또한 고유의 맛을 지닌 사람들, 이를 통해 맛있는 공간은 더욱 더 맛있어집니다.<br><br>#2. 주방설비가 완벽한 라이브커머스 촬영, 유튜브 촬영 / 식품촬영 스튜디오<br>*키친스튜디오 / 쿠킹스튜디오<br>- 3.2m의 큰 아일랜드 싱크대로 넉넉하게 방송하실 수 있습니다<br>- 인덕션 3구 및 냉장고, 전자레인지 등 다양한 주방설비<br>- 걱정없는 촬영 조명<br><br>#3. 제품 촬영 및 상세페이지 촬영<br>- 아기자기한 소품들과 제품 촬영 및 상세페이지 촬영<br><br>#4. 최대 12인 수용이 가능한 파티룸<br>-  파티<br>-  브라이덜샤워<br>-  소모임<br><br>#5. 영화관<br>- 고성능 빔 프로젝트와 웅장한 사운드로 영화 감상<br>(유튜브,넷플릭스,왓챠,애플tv 시청가능)<br><br>#6. 구비품목 : 레일조명, 싱크대, 주방집기, 쇼파, 전자레인지, 냉장고, 6~8인용 테이블, 쇼파, 빔프로젝트, 블루투스 스피커, 와이파이 및 랜선, 쇼파<br>',70000,10,'서울 영등포구 영신로17길 7-1','지하1층 맛있는공간','05043220311','공유주방,쿠킹스튜디오,파티룸,라이브커머스,키친스튜디오,빔프로젝터,넷플릭스,냉장고','Y',311,37.513783936142,126.90730885188,0,24,31,5);
--행 93
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'그린히어로 소셜키친','소중한 사람들과 행복을 만들어가는 공유주방입니다.','안녕하세요. <br>그린히어로 소셜키친은 행복을 만들어가는 일상 속 ‘생활 실험실’입니다.<br><br>기본적인 조리 도구와 양념, 최대 10명이 함께 식사할 수 있는 식탁과 식기를 구비하고 있어 여유 있는 요리와 식사가 가능합니다.<br>매일 오전, 오후 각각 1팀만 예약 가능한 구조로 신청자는 함께 요리하고, 오붓하게 요리한 음식을 먹으며 소중한 사람들과 즐겁고, 행복한 시간을 보낼 수 있습니다.<br><br>*예약 확정시 이용안내 문자 보내드립니다.',30000,6,'서울 영등포구 영등포로27길 13','1층 그린히어로 소셜키친','05043220790','공유주방,쿠킹,파티룸,주차가능','Y',418,37.522192586781,126.899111168481,10,22,24,5);
--행 94
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'당산골 소셜키친','당산골 공유주방은  빈티지 레트로 감성 공간입니다','안녕하세요.<br>당산골 공유주방은 <br>빈티지 레트로 감성 공간입니다.<br><br>정감있는 당산골에서 <br>편안하게 요리하고 <br>따듯한 밥 한끼 나눠먹으며 <br>일상에서 벗어난 설렘을 느껴보세요.',14000,4,'서울 영등포구 영등포로25길 17','당산골 소셜키친','05043220753','공유주방,빈티지,레트로,반려동물동반가능,주차가능,쿠킹','Y',391,37.5225589999749,126.898242451338,10,24,2,5);
--행 95
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[문래동] 갤러리 모스 moth','문래동의 작은 전시공간입니다 :)','네이버에 검색해주세요 ''갤러리 모스''<br>우리들의 숨결이 살아 숨쉬는 공간 ''갤러리 모스''<br><br>문래역과 영등포역의 중간지점_ 도로변에 위치한 갤러리 모스입니다. <br><br>누구나 쉽게 전시 관람과 대관이 가능하도록 공간을 구성했습니다. <br>일 7만원 (석사청구전의 경우 일 5만원으로 할인)의 저렴한 대관료로 전시를 꾸밀수 있는 공간입니다 :)',10000,20,'서울 영등포구 경인로 784-1','B1층, 갤러리 모스','05043220863','갤러리,전시,석사청구전','Y',766,37.5140419706538,126.900536025733,11,18,3,6);
--행 96
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'복합문화공간, 꼴라보하우스 문래','모든 컨텐츠가 가능한 폐공장 리모델링 복합문화공간','꼴라보하우스''는 압구정로데오 도산공원 근처에서 복합문화공간으로써, 아티스트 전시, 명품브랜드의 팝업스토어, 행사 및 파티 등, 이용객들에게 새로운 경험을 하는 브랜드입니다.<br><br>그리고 도산에서의 성공적인 운영을 통해,  문래동 폐공장을 리모델링하여, 다양한 문화전시 및 팝업공간을 운영하려고 합니다.<br><br>''예술문화창작촌'' 문래동에서 새롭게 시작하는 꼴라보하우스와 함께 새로운 컨텐츠를 제공할 수 있는 기회를 가져보세요.<br><br><br>꼴라보하우스 문래는 현재 문래동에서 가장 핫한 동네 중심부에 위치하고 있어, 접근성과 이용객들의 왕래가 많으며, 도보 5분 거리 내에 문래동 핫플이 모두 위치하고 있습니다.<br>',100000,100,'서울 영등포구 도림로139가길 8','꼴라보하우스 문래','05043220023','갤러리,복합문화공간,팝업스토어,인더스트리얼,전시,반려동물동반가능,반려견','Y',671,37.5138080322651,126.893167193298,9,22,4,6);
--행 97
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'본주짓수(문래)','체육관에 매트가 깔려있어 다칠 위험이 없습니다.','체육관 바닥에 매트가 깔려있어, 필라테스, 요가 등 매트가 필요한 운동 시 적합하며, 자녀들을 동반한 가족단위로도 이용 가능합니다.',40000,10,'서울 영등포구 선유로 58','2층 본주짓수(문래)','05043220013','체육관,운동시설,필라테스,요가,가족운동,운동공간,탈의실,샤워시설,매트','Y',363,37.5189944001757,126.889460833552,7,16,5,7);
--행 98
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[영등포 신길동]어서오짐','코시국 맞춤형 비대면 스포츠 특화 스튜디오','프라이빗한 복합문화공간 어서오짐입니다. 타인의 시선으로부터 자유롭고 효율적인 운동시간 즐기시기 바랍니다.<br><br>[운동공간]<br> - 더이상 운동기구를 기다리지 말고 집중력 있는 운동시간을 즐기세요. <br><br>[인바디]<br> - 막연한 체중계, 남이 읽어주는 인다비 숫자가 싫으셨던 분들, 퍼스널 인바디로 또 다른 나를 준비하세요.<br><br>[블루투스 스피커 &amp; 스마트티비]<br> - 자유로운 음악선곡과 여러분만의 영상으로 운동효과를 높이세요.<br><br>[셀프스튜디오]<br> - 이색적인 배경, 조명 장비로 당신의 소중한 기억을 남기세요.<br><br>[편의시설]<br> - 매장내 전용 화장실 및 탈의실 구비되어 있습니다.<br><br>* 매장 인근 도로에 주차 가능하나, 주정차 차량이 많아 불편하신 분들은 공영주차장을  이용해주세요.<br>1. 영등포본동 제2공영주차장 : 도보 8분 (10분당 100원)<br>2. 대신시장 노상상공영주차장 : 도보 3분 (10분당 200원)',8200,2,'서울 영등포구 신길동 154-9','지층','05043220035','운동시설,1인헬스장,무인헬스장,24시헬스장,비대면스포츠,복합문화공간,운동,탈의실','Y',555,37.5107427859904,126.915993482233,0,24,6,7);
--행 99
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[도산서재]영등포시장역 직결 건물','글 읽고 글 쓰는 공간, 도산서재','글 읽고 글 쓰는 공간 도산서재를 방문해주셔서 감사합니다.<br>도산서재는 영등포시장역2번출구와 직결된 건물에 위치하여 있습니다.<br><br>복잡한 세상에서 벗어나 이 곳에서 편안하고 느긋하게 당신만의 시간을 즐기시기 바랍니다.<br><br>독서 이외의 활동도 뭐든 좋습니다.<br>사색, 뜨개질, 창작활동, 회의, 그룹과외, 그림 그리기, 와인파티, 음악감상, 영화감상 등 뭐든 좋으니 당신만의 시간을 편안하고 소중하게 즐기셨으면 좋겠습니다.<br><br>당신만의 음악, 커피, 스크린이 준비되어 있습니다.<br>마음껏 사용하시고 머물다 가시기 바랍니다.',15000,8,'서울 영등포구 국회대로50길 20','B30호','05043220405','스터디룸,회의실,공유서재,독서','Y',432,37.5233963590387,126.905693415786,0,24,7,8);
--행 100
INSERT INTO SPACE (SPACE_NO, SPACE_TITLE, SPACE_SUBTITLE, SPACE_INFO, HOUR_PRICE, MAX_PEOPLE, ADDRESS_DEFAULT, ADDRESS_DETAIL, TEL, HASHTAG, SPACE_STATUS, COUNT, LATITUDE, LONGITUDE, OPEN_TIME, CLOSE_TIME, HOST_NO, STYPE_NO) VALUES (SEQ_SNO.NEXTVAL,'[당산] 그공간 - 스터디, 회의','우리가 진짜 회의하려고 만든 공간','스타트업 멤버들이 회의하기 위해 공간을 찾아 꾸렸습니다.<br>담백하게 회의에 집중할 수 있는 환경과, 역과 가까운 접근성을 누릴 수 있습니다.<br>회의와 세미나를 위해 필요한 것들을 심플하게 갖추었습니다. 시간효율과 생산성을 높일 수 있는 공간입니다.<br>짧고 집중적인 회의 혹은 사람들간의 세미나를 위해 "그공간"을 찾아주세요!<br>개인사업자, 스타트업 멤버들의 비정기적 업무공간으로도 환영입니다!',7000,6,'서울 영등포구 양평동1가 59','1층','05041381999','스터디룸,세미나,회의,스타트업,회의실','Y',190,37.5233454004265,126.890978771119,0,24,8,9);


COMMIT;